"""Download every dish's photograph from Wikimedia Commons and bundle it.

The photographs ship inside the app rather than being loaded from Commons at
runtime, for three reasons. The app claims to make no network calls and that
claim should stay true. A hotlink is a promise about someone else's bandwidth
that Gospel has no right to make. And a recipe with a broken image is a recipe
without an image, which is the one thing the library is not allowed to have.

Two sizes are written per dish. The plan tab can have a dozen plates on screen
at once and decoding a dozen thousand-pixel photographs to draw them at 96 px
is how an Android list starts dropping frames.

Every file's author and licence come down with it and are written into the
manifest, because most of these are CC BY-SA and attribution is a condition of
use, not a courtesy. The app shows them on the recipe screen and on the
references page.

Run:  python scripts/fetch_recipe_images.py [--force]
Out:  assets/recipes/<slug>.jpg         1000x600, the detail hero
      assets/recipes/<slug>-thumb.jpg    240x240, the plan list
      src/data/generated/recipe_images.json
      src/data/recipeImages.ts           static require() map for Metro
"""

from __future__ import annotations

import argparse
import io
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

from PIL import Image, ImageOps

sys.path.insert(0, str(Path(__file__).resolve().parent))

import wikimedia  # noqa: E402
from recipe_sources import SOURCES  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "assets" / "recipes"
MANIFEST = ROOT / "src" / "data" / "generated" / "recipe_images.json"

HERO = (1000, 600)
THUMB = (240, 240)
QUALITY = 82


def download(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": wikimedia.UA})
    for attempt in range(5):
        try:
            with urllib.request.urlopen(request, timeout=90) as response:
                return response.read()
        except urllib.error.HTTPError as error:
            if error.code in (429, 503):
                import time
                time.sleep(5 * (attempt + 1))
                continue
            raise
        except (urllib.error.URLError, TimeoutError, ConnectionError):
            import time
            time.sleep(3 * (attempt + 1))
    raise RuntimeError(f"could not download {url}")


def render(data: bytes, size: tuple[int, int], path: Path) -> None:
    """Centre-crop to `size` and write a progressive JPEG."""
    image = Image.open(io.BytesIO(data))
    # EXIF orientation is not applied by decoders on device; bake it in here or
    # a handful of photographs arrive sideways.
    image = ImageOps.exif_transpose(image)
    if image.mode != "RGB":
        image = image.convert("RGB")
    image = ImageOps.fit(image, size, method=Image.LANCZOS, centering=(0.5, 0.5))
    image.save(path, "JPEG", quality=QUALITY, optimize=True, progressive=True)


REQUIRE_MAP = ROOT / "src" / "data" / "recipeImages.ts"

REQUIRE_MAP_HEADER = '''/**
 * Every dish photograph, as a Metro asset.
 *
 * Generated by scripts/fetch_recipe_images.py - do not edit.
 *
 * Metro resolves `require` at build time from a string literal, so a bundled
 * image cannot be looked up by a path assembled at runtime. That is the whole
 * reason this file is written out rather than computed: one literal per
 * asset, so the bundler can see them all.
 *
 * Two sizes. `hero` is 1000x600 for the recipe screen; `thumb` is a 240x240
 * square for the plan list, where a dozen can be on screen at once and
 * decoding a dozen full-size photographs is how a list starts dropping
 * frames.
 */

import type { ImageSourcePropType } from 'react-native';

export interface RecipeImageAssets {
  hero: ImageSourcePropType;
  thumb: ImageSourcePropType;
}

export const recipeImages: Record<string, RecipeImageAssets> = {
'''

REQUIRE_MAP_FOOTER = '''};

/** The photograph for a recipe, or null if the slug is not in the library. */
export function recipeImage(slug: string): RecipeImageAssets | null {
  return recipeImages[slug] ?? null;
}
'''


def write_require_map(manifest: dict[str, dict]) -> None:
    lines = [REQUIRE_MAP_HEADER]
    for slug, entry in manifest.items():
        lines.append(
            f"  '{slug}': {{\n"
            f"    hero: require('../../assets/recipes/{entry['file']}'),\n"
            f"    thumb: require('../../assets/recipes/{entry['thumb']}'),\n"
            f"  }},\n"
        )
    lines.append(REQUIRE_MAP_FOOTER)
    REQUIRE_MAP.write_text("".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true",
                        help="re-download and re-render images already present")
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)

    manifest: dict[str, dict] = {}
    if MANIFEST.exists() and not args.force:
        manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))

    missing: list[str] = []
    total_bytes = 0

    for index, source in enumerate(SOURCES, 1):
        hero = OUT_DIR / f"{source.slug}.jpg"
        thumb = OUT_DIR / f"{source.slug}-thumb.jpg"
        done = hero.exists() and thumb.exists() and source.slug in manifest

        if done and not args.force:
            total_bytes += hero.stat().st_size + thumb.stat().st_size
            print(f"{index:3d} {source.slug:<22} cached", flush=True)
            continue

        chosen = source.image_file
        if chosen is None:
            page = wikimedia.wikipedia_page(source.wikipedia)
            if page is None:
                missing.append(f"{source.slug}: no Commons image")
                continue
            chosen = page.image_file
        credit = wikimedia.image_credit(chosen)
        if credit is None:
            missing.append(f"{source.slug}: no credit for {chosen}")
            continue

        try:
            data = download(credit.download_url)
            render(data, HERO, hero)
            render(data, THUMB, thumb)
        except Exception as error:                    # noqa: BLE001
            missing.append(f"{source.slug}: {type(error).__name__} {error}")
            continue

        manifest[source.slug] = {
            "file": hero.name,
            "thumb": thumb.name,
            "commons_file": credit.file,
            "author": credit.author,
            "license": credit.license,
            "license_url": credit.license_url,
            "source_url": credit.source_url,
        }
        size = hero.stat().st_size + thumb.stat().st_size
        total_bytes += size
        print(f"{index:3d} {source.slug:<22} {size / 1024:6.0f} kB  "
              f"{credit.license[:14]:<14} {credit.author[:34]}", flush=True)

    # Anything the spec dropped should not leave an orphan on disk.
    wanted = {s.slug for s in SOURCES}
    for slug in sorted(set(manifest) - wanted):
        del manifest[slug]
    for stale in sorted(OUT_DIR.glob("*.jpg")):
        slug = stale.stem.removesuffix("-thumb")
        if slug not in wanted:
            stale.unlink()
            print(f"    removed orphan {stale.name}")

    manifest = dict(sorted(manifest.items()))
    MANIFEST.write_text(
        json.dumps(manifest, indent=1, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    write_require_map(manifest)

    print(f"\n{len(manifest)} images, {total_bytes / 1024 / 1024:.1f} MB bundled")
    if missing:
        print(f"\n{len(missing)} MISSING:")
        for line in missing:
            print(f"  {line}")
        return 1
    if len(manifest) != len(SOURCES):
        print(f"\nexpected {len(SOURCES)} images, have {len(manifest)}")
        return 1
    print("every recipe has a photograph")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
