/**
 * Typed access to the FoodData Central ingredient panels.
 *
 * Generated by scripts/fetch_fdc_nutrition.py from USDA FDC. Nothing here
 * interprets the numbers - that is intake.ts's job. This module attaches types
 * and exposes the match metadata that makes the best-match-always policy
 * auditable.
 */

import raw from './generated/ingredient_nutrition.json';
import type { PanelIndex } from '@/domain/nutrition/intake';

export interface IngredientMatch {
  fdc_id: number;
  /** The FDC food this ingredient was matched to. */
  match_description: string | null;
  /** FDC's own relevance score. Relative, not a 0-1 confidence. */
  match_score: number;
  data_type: string | null;
  /** False when only the abridged search panel was available. */
  full_panel: boolean;
  per_100g: Record<string, number>;
}

export const ingredientMatches = raw as unknown as Record<string, IngredientMatch>;

/** The shape intake.ts consumes. */
export const ingredientPanels: PanelIndex = ingredientMatches;

/** How many ingredients resolved to an FDC food. */
export const matchedIngredientCount = Object.keys(ingredientMatches).length;
