/**
 * Every dish photograph, as a Metro asset.
 *
 * Generated by scripts/fetch_recipe_images.py - do not edit.
 *
 * Metro resolves `require` at build time from a string literal, so a bundled
 * image cannot be looked up by a path assembled at runtime. That is the whole
 * reason this file is written out rather than computed: one literal per
 * asset, so the bundler can see them all.
 *
 * Two sizes. `hero` is 1000x600 for the recipe screen; `thumb` is a 240x240
 * square for the plan list, where a dozen can be on screen at once and
 * decoding a dozen full-size photographs is how a list starts dropping
 * frames.
 */

import type { ImageSourcePropType } from 'react-native';

export interface RecipeImageAssets {
  hero: ImageSourcePropType;
  thumb: ImageSourcePropType;
}

export const recipeImages: Record<string, RecipeImageAssets> = {
  'abacha': {
    hero: require('../../assets/recipes/abacha.jpg'),
    thumb: require('../../assets/recipes/abacha-thumb.jpg'),
  },
  'abak-atama-soup': {
    hero: require('../../assets/recipes/abak-atama-soup.jpg'),
    thumb: require('../../assets/recipes/abak-atama-soup-thumb.jpg'),
  },
  'adobo-chicken': {
    hero: require('../../assets/recipes/adobo-chicken.jpg'),
    thumb: require('../../assets/recipes/adobo-chicken-thumb.jpg'),
  },
  'agedashi-tofu': {
    hero: require('../../assets/recipes/agedashi-tofu.jpg'),
    thumb: require('../../assets/recipes/agedashi-tofu-thumb.jpg'),
  },
  'aglio-e-olio': {
    hero: require('../../assets/recipes/aglio-e-olio.jpg'),
    thumb: require('../../assets/recipes/aglio-e-olio-thumb.jpg'),
  },
  'aji-de-gallina': {
    hero: require('../../assets/recipes/aji-de-gallina.jpg'),
    thumb: require('../../assets/recipes/aji-de-gallina-thumb.jpg'),
  },
  'akamu': {
    hero: require('../../assets/recipes/akamu.jpg'),
    thumb: require('../../assets/recipes/akamu-thumb.jpg'),
  },
  'albanian-vegetable-pie': {
    hero: require('../../assets/recipes/albanian-vegetable-pie.jpg'),
    thumb: require('../../assets/recipes/albanian-vegetable-pie-thumb.jpg'),
  },
  'albondigas': {
    hero: require('../../assets/recipes/albondigas.jpg'),
    thumb: require('../../assets/recipes/albondigas-thumb.jpg'),
  },
  'alfajores': {
    hero: require('../../assets/recipes/alfajores.jpg'),
    thumb: require('../../assets/recipes/alfajores-thumb.jpg'),
  },
  'anzac-biscuits': {
    hero: require('../../assets/recipes/anzac-biscuits.jpg'),
    thumb: require('../../assets/recipes/anzac-biscuits-thumb.jpg'),
  },
  'apple-brown-betty': {
    hero: require('../../assets/recipes/apple-brown-betty.jpg'),
    thumb: require('../../assets/recipes/apple-brown-betty-thumb.jpg'),
  },
  'apple-cobbler': {
    hero: require('../../assets/recipes/apple-cobbler.jpg'),
    thumb: require('../../assets/recipes/apple-cobbler-thumb.jpg'),
  },
  'apple-pie': {
    hero: require('../../assets/recipes/apple-pie.jpg'),
    thumb: require('../../assets/recipes/apple-pie-thumb.jpg'),
  },
  'apple-strudel': {
    hero: require('../../assets/recipes/apple-strudel.jpg'),
    thumb: require('../../assets/recipes/apple-strudel-thumb.jpg'),
  },
  'arambasici': {
    hero: require('../../assets/recipes/arambasici.jpg'),
    thumb: require('../../assets/recipes/arambasici-thumb.jpg'),
  },
  'arancini': {
    hero: require('../../assets/recipes/arancini.jpg'),
    thumb: require('../../assets/recipes/arancini-thumb.jpg'),
  },
  'arroz-con-pollo': {
    hero: require('../../assets/recipes/arroz-con-pollo.jpg'),
    thumb: require('../../assets/recipes/arroz-con-pollo-thumb.jpg'),
  },
  'arroz-negro': {
    hero: require('../../assets/recipes/arroz-negro.jpg'),
    thumb: require('../../assets/recipes/arroz-negro-thumb.jpg'),
  },
  'asun': {
    hero: require('../../assets/recipes/asun.jpg'),
    thumb: require('../../assets/recipes/asun-thumb.jpg'),
  },
  'austrian-napkin-dumpling': {
    hero: require('../../assets/recipes/austrian-napkin-dumpling.jpg'),
    thumb: require('../../assets/recipes/austrian-napkin-dumpling-thumb.jpg'),
  },
  'awug': {
    hero: require('../../assets/recipes/awug.jpg'),
    thumb: require('../../assets/recipes/awug-thumb.jpg'),
  },
  'baby-back-ribs': {
    hero: require('../../assets/recipes/baby-back-ribs.jpg'),
    thumb: require('../../assets/recipes/baby-back-ribs-thumb.jpg'),
  },
  'baguette': {
    hero: require('../../assets/recipes/baguette.jpg'),
    thumb: require('../../assets/recipes/baguette-thumb.jpg'),
  },
  'baingan-bartha': {
    hero: require('../../assets/recipes/baingan-bartha.jpg'),
    thumb: require('../../assets/recipes/baingan-bartha-thumb.jpg'),
  },
  'baked-beans': {
    hero: require('../../assets/recipes/baked-beans.jpg'),
    thumb: require('../../assets/recipes/baked-beans-thumb.jpg'),
  },
  'baked-ziti': {
    hero: require('../../assets/recipes/baked-ziti.jpg'),
    thumb: require('../../assets/recipes/baked-ziti-thumb.jpg'),
  },
  'baklava': {
    hero: require('../../assets/recipes/baklava.jpg'),
    thumb: require('../../assets/recipes/baklava-thumb.jpg'),
  },
  'banana-bread': {
    hero: require('../../assets/recipes/banana-bread.jpg'),
    thumb: require('../../assets/recipes/banana-bread-thumb.jpg'),
  },
  'banana-cream-pie': {
    hero: require('../../assets/recipes/banana-cream-pie.jpg'),
    thumb: require('../../assets/recipes/banana-cream-pie-thumb.jpg'),
  },
  'banana-split': {
    hero: require('../../assets/recipes/banana-split.jpg'),
    thumb: require('../../assets/recipes/banana-split-thumb.jpg'),
  },
  'banga-soup': {
    hero: require('../../assets/recipes/banga-soup.jpg'),
    thumb: require('../../assets/recipes/banga-soup-thumb.jpg'),
  },
  'bangers-and-mash': {
    hero: require('../../assets/recipes/bangers-and-mash.jpg'),
    thumb: require('../../assets/recipes/bangers-and-mash-thumb.jpg'),
  },
  'banh-chung': {
    hero: require('../../assets/recipes/banh-chung.jpg'),
    thumb: require('../../assets/recipes/banh-chung-thumb.jpg'),
  },
  'banh-mi': {
    hero: require('../../assets/recipes/banh-mi.jpg'),
    thumb: require('../../assets/recipes/banh-mi-thumb.jpg'),
  },
  'baozi': {
    hero: require('../../assets/recipes/baozi.jpg'),
    thumb: require('../../assets/recipes/baozi-thumb.jpg'),
  },
  'barbecued-spare-ribs': {
    hero: require('../../assets/recipes/barbecued-spare-ribs.jpg'),
    thumb: require('../../assets/recipes/barbecued-spare-ribs-thumb.jpg'),
  },
  'basbousa': {
    hero: require('../../assets/recipes/basbousa.jpg'),
    thumb: require('../../assets/recipes/basbousa-thumb.jpg'),
  },
  'bbq-ribs': {
    hero: require('../../assets/recipes/bbq-ribs.jpg'),
    thumb: require('../../assets/recipes/bbq-ribs-thumb.jpg'),
  },
  'beef-bourguignon': {
    hero: require('../../assets/recipes/beef-bourguignon.jpg'),
    thumb: require('../../assets/recipes/beef-bourguignon-thumb.jpg'),
  },
  'beef-heart-kabobs': {
    hero: require('../../assets/recipes/beef-heart-kabobs.jpg'),
    thumb: require('../../assets/recipes/beef-heart-kabobs-thumb.jpg'),
  },
  'bell-pepper-chili': {
    hero: require('../../assets/recipes/bell-pepper-chili.jpg'),
    thumb: require('../../assets/recipes/bell-pepper-chili-thumb.jpg'),
  },
  'benachin': {
    hero: require('../../assets/recipes/benachin.jpg'),
    thumb: require('../../assets/recipes/benachin-thumb.jpg'),
  },
  'bibimbap': {
    hero: require('../../assets/recipes/bibimbap.jpg'),
    thumb: require('../../assets/recipes/bibimbap-thumb.jpg'),
  },
  'bicol-express': {
    hero: require('../../assets/recipes/bicol-express.jpg'),
    thumb: require('../../assets/recipes/bicol-express-thumb.jpg'),
  },
  'binagoongan': {
    hero: require('../../assets/recipes/binagoongan.jpg'),
    thumb: require('../../assets/recipes/binagoongan-thumb.jpg'),
  },
  'bint-as-sahn': {
    hero: require('../../assets/recipes/bint-as-sahn.jpg'),
    thumb: require('../../assets/recipes/bint-as-sahn-thumb.jpg'),
  },
  'biscotti': {
    hero: require('../../assets/recipes/biscotti.jpg'),
    thumb: require('../../assets/recipes/biscotti-thumb.jpg'),
  },
  'biscuits': {
    hero: require('../../assets/recipes/biscuits.jpg'),
    thumb: require('../../assets/recipes/biscuits-thumb.jpg'),
  },
  'black-forest-cake': {
    hero: require('../../assets/recipes/black-forest-cake.jpg'),
    thumb: require('../../assets/recipes/black-forest-cake-thumb.jpg'),
  },
  'bleskiver': {
    hero: require('../../assets/recipes/bleskiver.jpg'),
    thumb: require('../../assets/recipes/bleskiver-thumb.jpg'),
  },
  'bliny': {
    hero: require('../../assets/recipes/bliny.jpg'),
    thumb: require('../../assets/recipes/bliny-thumb.jpg'),
  },
  'blt': {
    hero: require('../../assets/recipes/blt.jpg'),
    thumb: require('../../assets/recipes/blt-thumb.jpg'),
  },
  'bltkake': {
    hero: require('../../assets/recipes/bltkake.jpg'),
    thumb: require('../../assets/recipes/bltkake-thumb.jpg'),
  },
  'blueberry-muffin': {
    hero: require('../../assets/recipes/blueberry-muffin.jpg'),
    thumb: require('../../assets/recipes/blueberry-muffin-thumb.jpg'),
  },
  'bo-bia': {
    hero: require('../../assets/recipes/bo-bia.jpg'),
    thumb: require('../../assets/recipes/bo-bia-thumb.jpg'),
  },
  'bobotie': {
    hero: require('../../assets/recipes/bobotie.jpg'),
    thumb: require('../../assets/recipes/bobotie-thumb.jpg'),
  },
  'boliche': {
    hero: require('../../assets/recipes/boliche.jpg'),
    thumb: require('../../assets/recipes/boliche-thumb.jpg'),
  },
  'bolognese': {
    hero: require('../../assets/recipes/bolognese.jpg'),
    thumb: require('../../assets/recipes/bolognese-thumb.jpg'),
  },
  'bonda': {
    hero: require('../../assets/recipes/bonda.jpg'),
    thumb: require('../../assets/recipes/bonda-thumb.jpg'),
  },
  'borscht': {
    hero: require('../../assets/recipes/borscht.jpg'),
    thumb: require('../../assets/recipes/borscht-thumb.jpg'),
  },
  'bouillabaisse': {
    hero: require('../../assets/recipes/bouillabaisse.jpg'),
    thumb: require('../../assets/recipes/bouillabaisse-thumb.jpg'),
  },
  'braai': {
    hero: require('../../assets/recipes/braai.jpg'),
    thumb: require('../../assets/recipes/braai-thumb.jpg'),
  },
  'bread-pudding': {
    hero: require('../../assets/recipes/bread-pudding.jpg'),
    thumb: require('../../assets/recipes/bread-pudding-thumb.jpg'),
  },
  'bruschetta': {
    hero: require('../../assets/recipes/bruschetta.jpg'),
    thumb: require('../../assets/recipes/bruschetta-thumb.jpg'),
  },
  'buchteln': {
    hero: require('../../assets/recipes/buchteln.jpg'),
    thumb: require('../../assets/recipes/buchteln-thumb.jpg'),
  },
  'buckwheat-crepes': {
    hero: require('../../assets/recipes/buckwheat-crepes.jpg'),
    thumb: require('../../assets/recipes/buckwheat-crepes-thumb.jpg'),
  },
  'buffalo-wings': {
    hero: require('../../assets/recipes/buffalo-wings.jpg'),
    thumb: require('../../assets/recipes/buffalo-wings-thumb.jpg'),
  },
  'bulgarian-tripe-soup': {
    hero: require('../../assets/recipes/bulgarian-tripe-soup.jpg'),
    thumb: require('../../assets/recipes/bulgarian-tripe-soup-thumb.jpg'),
  },
  'bulgogi': {
    hero: require('../../assets/recipes/bulgogi.jpg'),
    thumb: require('../../assets/recipes/bulgogi-thumb.jpg'),
  },
  'bunny-chow': {
    hero: require('../../assets/recipes/bunny-chow.jpg'),
    thumb: require('../../assets/recipes/bunny-chow-thumb.jpg'),
  },
  'bunuelos': {
    hero: require('../../assets/recipes/bunuelos.jpg'),
    thumb: require('../../assets/recipes/bunuelos-thumb.jpg'),
  },
  'burple-nurples': {
    hero: require('../../assets/recipes/burple-nurples.jpg'),
    thumb: require('../../assets/recipes/burple-nurples-thumb.jpg'),
  },
  'burrito': {
    hero: require('../../assets/recipes/burrito.jpg'),
    thumb: require('../../assets/recipes/burrito-thumb.jpg'),
  },
  'butter-chicken': {
    hero: require('../../assets/recipes/butter-chicken.jpg'),
    thumb: require('../../assets/recipes/butter-chicken-thumb.jpg'),
  },
  'cacio-e-pepe': {
    hero: require('../../assets/recipes/cacio-e-pepe.jpg'),
    thumb: require('../../assets/recipes/cacio-e-pepe-thumb.jpg'),
  },
  'caesar-salad': {
    hero: require('../../assets/recipes/caesar-salad.jpg'),
    thumb: require('../../assets/recipes/caesar-salad-thumb.jpg'),
  },
  'callaloo': {
    hero: require('../../assets/recipes/callaloo.jpg'),
    thumb: require('../../assets/recipes/callaloo-thumb.jpg'),
  },
  'calzone': {
    hero: require('../../assets/recipes/calzone.jpg'),
    thumb: require('../../assets/recipes/calzone-thumb.jpg'),
  },
  'camotes-enmielados': {
    hero: require('../../assets/recipes/camotes-enmielados.jpg'),
    thumb: require('../../assets/recipes/camotes-enmielados-thumb.jpg'),
  },
  'cantonese-crispy-fried-chicken': {
    hero: require('../../assets/recipes/cantonese-crispy-fried-chicken.jpg'),
    thumb: require('../../assets/recipes/cantonese-crispy-fried-chicken-thumb.jpg'),
  },
  'caprese': {
    hero: require('../../assets/recipes/caprese.jpg'),
    thumb: require('../../assets/recipes/caprese-thumb.jpg'),
  },
  'caramel-squares': {
    hero: require('../../assets/recipes/caramel-squares.jpg'),
    thumb: require('../../assets/recipes/caramel-squares-thumb.jpg'),
  },
  'carbonara': {
    hero: require('../../assets/recipes/carbonara.jpg'),
    thumb: require('../../assets/recipes/carbonara-thumb.jpg'),
  },
  'carpetbag-steak': {
    hero: require('../../assets/recipes/carpetbag-steak.jpg'),
    thumb: require('../../assets/recipes/carpetbag-steak-thumb.jpg'),
  },
  'carrot-cake': {
    hero: require('../../assets/recipes/carrot-cake.jpg'),
    thumb: require('../../assets/recipes/carrot-cake-thumb.jpg'),
  },
  'cassoulet': {
    hero: require('../../assets/recipes/cassoulet.jpg'),
    thumb: require('../../assets/recipes/cassoulet-thumb.jpg'),
  },
  'cazuela-gallega': {
    hero: require('../../assets/recipes/cazuela-gallega.jpg'),
    thumb: require('../../assets/recipes/cazuela-gallega-thumb.jpg'),
  },
  'chakalaka': {
    hero: require('../../assets/recipes/chakalaka.jpg'),
    thumb: require('../../assets/recipes/chakalaka-thumb.jpg'),
  },
  'challah': {
    hero: require('../../assets/recipes/challah.jpg'),
    thumb: require('../../assets/recipes/challah-thumb.jpg'),
  },
  'chalupa': {
    hero: require('../../assets/recipes/chalupa.jpg'),
    thumb: require('../../assets/recipes/chalupa-thumb.jpg'),
  },
  'champorado': {
    hero: require('../../assets/recipes/champorado.jpg'),
    thumb: require('../../assets/recipes/champorado-thumb.jpg'),
  },
  'chapati': {
    hero: require('../../assets/recipes/chapati.jpg'),
    thumb: require('../../assets/recipes/chapati-thumb.jpg'),
  },
  'char-siu': {
    hero: require('../../assets/recipes/char-siu.jpg'),
    thumb: require('../../assets/recipes/char-siu-thumb.jpg'),
  },
  'cheeseburger': {
    hero: require('../../assets/recipes/cheeseburger.jpg'),
    thumb: require('../../assets/recipes/cheeseburger-thumb.jpg'),
  },
  'cheeseburgers': {
    hero: require('../../assets/recipes/cheeseburgers.jpg'),
    thumb: require('../../assets/recipes/cheeseburgers-thumb.jpg'),
  },
  'chicken-a-la-king': {
    hero: require('../../assets/recipes/chicken-a-la-king.jpg'),
    thumb: require('../../assets/recipes/chicken-a-la-king-thumb.jpg'),
  },
  'chicken-alfredo': {
    hero: require('../../assets/recipes/chicken-alfredo.jpg'),
    thumb: require('../../assets/recipes/chicken-alfredo-thumb.jpg'),
  },
  'chicken-and-dumplings': {
    hero: require('../../assets/recipes/chicken-and-dumplings.jpg'),
    thumb: require('../../assets/recipes/chicken-and-dumplings-thumb.jpg'),
  },
  'chicken-biryani': {
    hero: require('../../assets/recipes/chicken-biryani.jpg'),
    thumb: require('../../assets/recipes/chicken-biryani-thumb.jpg'),
  },
  'chicken-curry': {
    hero: require('../../assets/recipes/chicken-curry.jpg'),
    thumb: require('../../assets/recipes/chicken-curry-thumb.jpg'),
  },
  'chicken-marsala': {
    hero: require('../../assets/recipes/chicken-marsala.jpg'),
    thumb: require('../../assets/recipes/chicken-marsala-thumb.jpg'),
  },
  'chicken-parmesan': {
    hero: require('../../assets/recipes/chicken-parmesan.jpg'),
    thumb: require('../../assets/recipes/chicken-parmesan-thumb.jpg'),
  },
  'chicken-riggies': {
    hero: require('../../assets/recipes/chicken-riggies.jpg'),
    thumb: require('../../assets/recipes/chicken-riggies-thumb.jpg'),
  },
  'chicken-sopas': {
    hero: require('../../assets/recipes/chicken-sopas.jpg'),
    thumb: require('../../assets/recipes/chicken-sopas-thumb.jpg'),
  },
  'chicken-soup': {
    hero: require('../../assets/recipes/chicken-soup.jpg'),
    thumb: require('../../assets/recipes/chicken-soup-thumb.jpg'),
  },
  'chicken-tetrazzini': {
    hero: require('../../assets/recipes/chicken-tetrazzini.jpg'),
    thumb: require('../../assets/recipes/chicken-tetrazzini-thumb.jpg'),
  },
  'chicken-tikka': {
    hero: require('../../assets/recipes/chicken-tikka.jpg'),
    thumb: require('../../assets/recipes/chicken-tikka-thumb.jpg'),
  },
  'chicken-vindaloo': {
    hero: require('../../assets/recipes/chicken-vindaloo.jpg'),
    thumb: require('../../assets/recipes/chicken-vindaloo-thumb.jpg'),
  },
  'chilaquiles': {
    hero: require('../../assets/recipes/chilaquiles.jpg'),
    thumb: require('../../assets/recipes/chilaquiles-thumb.jpg'),
  },
  'chimichurri': {
    hero: require('../../assets/recipes/chimichurri.jpg'),
    thumb: require('../../assets/recipes/chimichurri-thumb.jpg'),
  },
  'chivito': {
    hero: require('../../assets/recipes/chivito.jpg'),
    thumb: require('../../assets/recipes/chivito-thumb.jpg'),
  },
  'chocolate-mousse': {
    hero: require('../../assets/recipes/chocolate-mousse.jpg'),
    thumb: require('../../assets/recipes/chocolate-mousse-thumb.jpg'),
  },
  'chokladboll': {
    hero: require('../../assets/recipes/chokladboll.jpg'),
    thumb: require('../../assets/recipes/chokladboll-thumb.jpg'),
  },
  'cholley': {
    hero: require('../../assets/recipes/cholley.jpg'),
    thumb: require('../../assets/recipes/cholley-thumb.jpg'),
  },
  'choucroute': {
    hero: require('../../assets/recipes/choucroute.jpg'),
    thumb: require('../../assets/recipes/choucroute-thumb.jpg'),
  },
  'chow-mein': {
    hero: require('../../assets/recipes/chow-mein.jpg'),
    thumb: require('../../assets/recipes/chow-mein-thumb.jpg'),
  },
  'chraime': {
    hero: require('../../assets/recipes/chraime.jpg'),
    thumb: require('../../assets/recipes/chraime-thumb.jpg'),
  },
  'christmas-cake': {
    hero: require('../../assets/recipes/christmas-cake.jpg'),
    thumb: require('../../assets/recipes/christmas-cake-thumb.jpg'),
  },
  'christmas-pudding': {
    hero: require('../../assets/recipes/christmas-pudding.jpg'),
    thumb: require('../../assets/recipes/christmas-pudding-thumb.jpg'),
  },
  'chupaqueso': {
    hero: require('../../assets/recipes/chupaqueso.jpg'),
    thumb: require('../../assets/recipes/chupaqueso-thumb.jpg'),
  },
  'churros': {
    hero: require('../../assets/recipes/churros.jpg'),
    thumb: require('../../assets/recipes/churros-thumb.jpg'),
  },
  'ciabatta': {
    hero: require('../../assets/recipes/ciabatta.jpg'),
    thumb: require('../../assets/recipes/ciabatta-thumb.jpg'),
  },
  'cinnamon-bun': {
    hero: require('../../assets/recipes/cinnamon-bun.jpg'),
    thumb: require('../../assets/recipes/cinnamon-bun-thumb.jpg'),
  },
  'cioppino': {
    hero: require('../../assets/recipes/cioppino.jpg'),
    thumb: require('../../assets/recipes/cioppino-thumb.jpg'),
  },
  'clam-chowder': {
    hero: require('../../assets/recipes/clam-chowder.jpg'),
    thumb: require('../../assets/recipes/clam-chowder-thumb.jpg'),
  },
  'coconut-chicken': {
    hero: require('../../assets/recipes/coconut-chicken.jpg'),
    thumb: require('../../assets/recipes/coconut-chicken-thumb.jpg'),
  },
  'coconut-rice': {
    hero: require('../../assets/recipes/coconut-rice.jpg'),
    thumb: require('../../assets/recipes/coconut-rice-thumb.jpg'),
  },
  'cola': {
    hero: require('../../assets/recipes/cola.jpg'),
    thumb: require('../../assets/recipes/cola-thumb.jpg'),
  },
  'coleslaw': {
    hero: require('../../assets/recipes/coleslaw.jpg'),
    thumb: require('../../assets/recipes/coleslaw-thumb.jpg'),
  },
  'com-chien': {
    hero: require('../../assets/recipes/com-chien.jpg'),
    thumb: require('../../assets/recipes/com-chien-thumb.jpg'),
  },
  'congee': {
    hero: require('../../assets/recipes/congee.jpg'),
    thumb: require('../../assets/recipes/congee-thumb.jpg'),
  },
  'consomme': {
    hero: require('../../assets/recipes/consomme.jpg'),
    thumb: require('../../assets/recipes/consomme-thumb.jpg'),
  },
  'coq-au-vin': {
    hero: require('../../assets/recipes/coq-au-vin.jpg'),
    thumb: require('../../assets/recipes/coq-au-vin-thumb.jpg'),
  },
  'corn-chowder': {
    hero: require('../../assets/recipes/corn-chowder.jpg'),
    thumb: require('../../assets/recipes/corn-chowder-thumb.jpg'),
  },
  'cornbread': {
    hero: require('../../assets/recipes/cornbread.jpg'),
    thumb: require('../../assets/recipes/cornbread-thumb.jpg'),
  },
  'corned-beef-pie': {
    hero: require('../../assets/recipes/corned-beef-pie.jpg'),
    thumb: require('../../assets/recipes/corned-beef-pie-thumb.jpg'),
  },
  'coronation-chicken': {
    hero: require('../../assets/recipes/coronation-chicken.jpg'),
    thumb: require('../../assets/recipes/coronation-chicken-thumb.jpg'),
  },
  'cream-puff': {
    hero: require('../../assets/recipes/cream-puff.jpg'),
    thumb: require('../../assets/recipes/cream-puff-thumb.jpg'),
  },
  'creme-brulee': {
    hero: require('../../assets/recipes/creme-brulee.jpg'),
    thumb: require('../../assets/recipes/creme-brulee-thumb.jpg'),
  },
  'crepes': {
    hero: require('../../assets/recipes/crepes.jpg'),
    thumb: require('../../assets/recipes/crepes-thumb.jpg'),
  },
  'croque-monsieur': {
    hero: require('../../assets/recipes/croque-monsieur.jpg'),
    thumb: require('../../assets/recipes/croque-monsieur-thumb.jpg'),
  },
  'croquetas': {
    hero: require('../../assets/recipes/croquetas.jpg'),
    thumb: require('../../assets/recipes/croquetas-thumb.jpg'),
  },
  'cupcakes': {
    hero: require('../../assets/recipes/cupcakes.jpg'),
    thumb: require('../../assets/recipes/cupcakes-thumb.jpg'),
  },
  'curtido': {
    hero: require('../../assets/recipes/curtido.jpg'),
    thumb: require('../../assets/recipes/curtido-thumb.jpg'),
  },
  'dal-makhani': {
    hero: require('../../assets/recipes/dal-makhani.jpg'),
    thumb: require('../../assets/recipes/dal-makhani-thumb.jpg'),
  },
  'deep-dish-pizza': {
    hero: require('../../assets/recipes/deep-dish-pizza.jpg'),
    thumb: require('../../assets/recipes/deep-dish-pizza-thumb.jpg'),
  },
  'deep-fried-chiles-stuffed-with-potato': {
    hero: require('../../assets/recipes/deep-fried-chiles-stuffed-with-potato.jpg'),
    thumb: require('../../assets/recipes/deep-fried-chiles-stuffed-with-potato-thumb.jpg'),
  },
  'denver-omelet': {
    hero: require('../../assets/recipes/denver-omelet.jpg'),
    thumb: require('../../assets/recipes/denver-omelet-thumb.jpg'),
  },
  'dhokla': {
    hero: require('../../assets/recipes/dhokla.jpg'),
    thumb: require('../../assets/recipes/dhokla-thumb.jpg'),
  },
  'dinuguan': {
    hero: require('../../assets/recipes/dinuguan.jpg'),
    thumb: require('../../assets/recipes/dinuguan-thumb.jpg'),
  },
  'dirty-rice': {
    hero: require('../../assets/recipes/dirty-rice.jpg'),
    thumb: require('../../assets/recipes/dirty-rice-thumb.jpg'),
  },
  'dolma': {
    hero: require('../../assets/recipes/dolma.jpg'),
    thumb: require('../../assets/recipes/dolma-thumb.jpg'),
  },
  'domoda': {
    hero: require('../../assets/recipes/domoda.jpg'),
    thumb: require('../../assets/recipes/domoda-thumb.jpg'),
  },
  'doner-kebab': {
    hero: require('../../assets/recipes/doner-kebab.jpg'),
    thumb: require('../../assets/recipes/doner-kebab-thumb.jpg'),
  },
  'duck-a-l-orange': {
    hero: require('../../assets/recipes/duck-a-l-orange.jpg'),
    thumb: require('../../assets/recipes/duck-a-l-orange-thumb.jpg'),
  },
  'dutch-apple-fritters': {
    hero: require('../../assets/recipes/dutch-apple-fritters.jpg'),
    thumb: require('../../assets/recipes/dutch-apple-fritters-thumb.jpg'),
  },
  'eclairs': {
    hero: require('../../assets/recipes/eclairs.jpg'),
    thumb: require('../../assets/recipes/eclairs-thumb.jpg'),
  },
  'egg-roll': {
    hero: require('../../assets/recipes/egg-roll.jpg'),
    thumb: require('../../assets/recipes/egg-roll-thumb.jpg'),
  },
  'eggplant-parmesan': {
    hero: require('../../assets/recipes/eggplant-parmesan.jpg'),
    thumb: require('../../assets/recipes/eggplant-parmesan-thumb.jpg'),
  },
  'egusi-soup': {
    hero: require('../../assets/recipes/egusi-soup.jpg'),
    thumb: require('../../assets/recipes/egusi-soup-thumb.jpg'),
  },
  'egyptian-cabbage-rolls': {
    hero: require('../../assets/recipes/egyptian-cabbage-rolls.jpg'),
    thumb: require('../../assets/recipes/egyptian-cabbage-rolls-thumb.jpg'),
  },
  'egyptian-grilled-pigeon': {
    hero: require('../../assets/recipes/egyptian-grilled-pigeon.jpg'),
    thumb: require('../../assets/recipes/egyptian-grilled-pigeon-thumb.jpg'),
  },
  'egyptian-lentil-soup': {
    hero: require('../../assets/recipes/egyptian-lentil-soup.jpg'),
    thumb: require('../../assets/recipes/egyptian-lentil-soup-thumb.jpg'),
  },
  'egyptian-meatballs': {
    hero: require('../../assets/recipes/egyptian-meatballs.jpg'),
    thumb: require('../../assets/recipes/egyptian-meatballs-thumb.jpg'),
  },
  'egyptian-milk-pudding': {
    hero: require('../../assets/recipes/egyptian-milk-pudding.jpg'),
    thumb: require('../../assets/recipes/egyptian-milk-pudding-thumb.jpg'),
  },
  'egyptian-okra-stew': {
    hero: require('../../assets/recipes/egyptian-okra-stew.jpg'),
    thumb: require('../../assets/recipes/egyptian-okra-stew-thumb.jpg'),
  },
  'egyptian-stuffed-grape-leaves': {
    hero: require('../../assets/recipes/egyptian-stuffed-grape-leaves.jpg'),
    thumb: require('../../assets/recipes/egyptian-stuffed-grape-leaves-thumb.jpg'),
  },
  'ekpang-nkukwo': {
    hero: require('../../assets/recipes/ekpang-nkukwo.jpg'),
    thumb: require('../../assets/recipes/ekpang-nkukwo-thumb.jpg'),
  },
  'empanadas': {
    hero: require('../../assets/recipes/empanadas.jpg'),
    thumb: require('../../assets/recipes/empanadas-thumb.jpg'),
  },
  'english-muffins': {
    hero: require('../../assets/recipes/english-muffins.jpg'),
    thumb: require('../../assets/recipes/english-muffins-thumb.jpg'),
  },
  'erwtensoep': {
    hero: require('../../assets/recipes/erwtensoep.jpg'),
    thumb: require('../../assets/recipes/erwtensoep-thumb.jpg'),
  },
  'euneo-juk': {
    hero: require('../../assets/recipes/euneo-juk.jpg'),
    thumb: require('../../assets/recipes/euneo-juk-thumb.jpg'),
  },
  'fabada': {
    hero: require('../../assets/recipes/fabada.jpg'),
    thumb: require('../../assets/recipes/fabada-thumb.jpg'),
  },
  'fabes-con-almejas': {
    hero: require('../../assets/recipes/fabes-con-almejas.jpg'),
    thumb: require('../../assets/recipes/fabes-con-almejas-thumb.jpg'),
  },
  'falafel': {
    hero: require('../../assets/recipes/falafel.jpg'),
    thumb: require('../../assets/recipes/falafel-thumb.jpg'),
  },
  'farikal': {
    hero: require('../../assets/recipes/farikal.jpg'),
    thumb: require('../../assets/recipes/farikal-thumb.jpg'),
  },
  'farofa': {
    hero: require('../../assets/recipes/farofa.jpg'),
    thumb: require('../../assets/recipes/farofa-thumb.jpg'),
  },
  'feijoada': {
    hero: require('../../assets/recipes/feijoada.jpg'),
    thumb: require('../../assets/recipes/feijoada-thumb.jpg'),
  },
  'figgy-pudding': {
    hero: require('../../assets/recipes/figgy-pudding.jpg'),
    thumb: require('../../assets/recipes/figgy-pudding-thumb.jpg'),
  },
  'filipino-style-spaghetti': {
    hero: require('../../assets/recipes/filipino-style-spaghetti.jpg'),
    thumb: require('../../assets/recipes/filipino-style-spaghetti-thumb.jpg'),
  },
  'fish-and-chips': {
    hero: require('../../assets/recipes/fish-and-chips.jpg'),
    thumb: require('../../assets/recipes/fish-and-chips-thumb.jpg'),
  },
  'flammekueche': {
    hero: require('../../assets/recipes/flammekueche.jpg'),
    thumb: require('../../assets/recipes/flammekueche-thumb.jpg'),
  },
  'fleischkrapfen': {
    hero: require('../../assets/recipes/fleischkrapfen.jpg'),
    thumb: require('../../assets/recipes/fleischkrapfen-thumb.jpg'),
  },
  'fleischnacka': {
    hero: require('../../assets/recipes/fleischnacka.jpg'),
    thumb: require('../../assets/recipes/fleischnacka-thumb.jpg'),
  },
  'focaccia': {
    hero: require('../../assets/recipes/focaccia.jpg'),
    thumb: require('../../assets/recipes/focaccia-thumb.jpg'),
  },
  'french-canadian-shepherd-s-pie': {
    hero: require('../../assets/recipes/french-canadian-shepherd-s-pie.jpg'),
    thumb: require('../../assets/recipes/french-canadian-shepherd-s-pie-thumb.jpg'),
  },
  'french-omelette': {
    hero: require('../../assets/recipes/french-omelette.jpg'),
    thumb: require('../../assets/recipes/french-omelette-thumb.jpg'),
  },
  'french-onion-soup': {
    hero: require('../../assets/recipes/french-onion-soup.jpg'),
    thumb: require('../../assets/recipes/french-onion-soup-thumb.jpg'),
  },
  'french-toast': {
    hero: require('../../assets/recipes/french-toast.jpg'),
    thumb: require('../../assets/recipes/french-toast-thumb.jpg'),
  },
  'fresh-mozzarella-bruschetta': {
    hero: require('../../assets/recipes/fresh-mozzarella-bruschetta.jpg'),
    thumb: require('../../assets/recipes/fresh-mozzarella-bruschetta-thumb.jpg'),
  },
  'fried-chicken': {
    hero: require('../../assets/recipes/fried-chicken.jpg'),
    thumb: require('../../assets/recipes/fried-chicken-thumb.jpg'),
  },
  'fried-eggs': {
    hero: require('../../assets/recipes/fried-eggs.jpg'),
    thumb: require('../../assets/recipes/fried-eggs-thumb.jpg'),
  },
  'fried-green-tomatoes': {
    hero: require('../../assets/recipes/fried-green-tomatoes.jpg'),
    thumb: require('../../assets/recipes/fried-green-tomatoes-thumb.jpg'),
  },
  'fried-rice': {
    hero: require('../../assets/recipes/fried-rice.jpg'),
    thumb: require('../../assets/recipes/fried-rice-thumb.jpg'),
  },
  'fried-shrimp': {
    hero: require('../../assets/recipes/fried-shrimp.jpg'),
    thumb: require('../../assets/recipes/fried-shrimp-thumb.jpg'),
  },
  'frijoles-antioquenos': {
    hero: require('../../assets/recipes/frijoles-antioquenos.jpg'),
    thumb: require('../../assets/recipes/frijoles-antioquenos-thumb.jpg'),
  },
  'frikadeller': {
    hero: require('../../assets/recipes/frikadeller.jpg'),
    thumb: require('../../assets/recipes/frikadeller-thumb.jpg'),
  },
  'frittaten-soup': {
    hero: require('../../assets/recipes/frittaten-soup.jpg'),
    thumb: require('../../assets/recipes/frittaten-soup-thumb.jpg'),
  },
  'ful-medames': {
    hero: require('../../assets/recipes/ful-medames.jpg'),
    thumb: require('../../assets/recipes/ful-medames-thumb.jpg'),
  },
  'full-english': {
    hero: require('../../assets/recipes/full-english.jpg'),
    thumb: require('../../assets/recipes/full-english-thumb.jpg'),
  },
  'gajjar-halwa': {
    hero: require('../../assets/recipes/gajjar-halwa.jpg'),
    thumb: require('../../assets/recipes/gajjar-halwa-thumb.jpg'),
  },
  'galaktoboureko': {
    hero: require('../../assets/recipes/galaktoboureko.jpg'),
    thumb: require('../../assets/recipes/galaktoboureko-thumb.jpg'),
  },
  'galbi': {
    hero: require('../../assets/recipes/galbi.jpg'),
    thumb: require('../../assets/recipes/galbi-thumb.jpg'),
  },
  'gallo-pinto': {
    hero: require('../../assets/recipes/gallo-pinto.jpg'),
    thumb: require('../../assets/recipes/gallo-pinto-thumb.jpg'),
  },
  'gambas-al-ajillo': {
    hero: require('../../assets/recipes/gambas-al-ajillo.jpg'),
    thumb: require('../../assets/recipes/gambas-al-ajillo-thumb.jpg'),
  },
  'gazpacho': {
    hero: require('../../assets/recipes/gazpacho.jpg'),
    thumb: require('../../assets/recipes/gazpacho-thumb.jpg'),
  },
  'general-tso-s-chicken': {
    hero: require('../../assets/recipes/general-tso-s-chicken.jpg'),
    thumb: require('../../assets/recipes/general-tso-s-chicken-thumb.jpg'),
  },
  'germknodel': {
    hero: require('../../assets/recipes/germknodel.jpg'),
    thumb: require('../../assets/recipes/germknodel-thumb.jpg'),
  },
  'ghavoot': {
    hero: require('../../assets/recipes/ghavoot.jpg'),
    thumb: require('../../assets/recipes/ghavoot-thumb.jpg'),
  },
  'ghevar': {
    hero: require('../../assets/recipes/ghevar.jpg'),
    thumb: require('../../assets/recipes/ghevar-thumb.jpg'),
  },
  'ghormeh-sabzi': {
    hero: require('../../assets/recipes/ghormeh-sabzi.jpg'),
    thumb: require('../../assets/recipes/ghormeh-sabzi-thumb.jpg'),
  },
  'gimbap': {
    hero: require('../../assets/recipes/gimbap.jpg'),
    thumb: require('../../assets/recipes/gimbap-thumb.jpg'),
  },
  'gingerbread': {
    hero: require('../../assets/recipes/gingerbread.jpg'),
    thumb: require('../../assets/recipes/gingerbread-thumb.jpg'),
  },
  'gnocchi': {
    hero: require('../../assets/recipes/gnocchi.jpg'),
    thumb: require('../../assets/recipes/gnocchi-thumb.jpg'),
  },
  'gooey-butter-cake': {
    hero: require('../../assets/recipes/gooey-butter-cake.jpg'),
    thumb: require('../../assets/recipes/gooey-butter-cake-thumb.jpg'),
  },
  'goulash': {
    hero: require('../../assets/recipes/goulash.jpg'),
    thumb: require('../../assets/recipes/goulash-thumb.jpg'),
  },
  'gozleme': {
    hero: require('../../assets/recipes/gozleme.jpg'),
    thumb: require('../../assets/recipes/gozleme-thumb.jpg'),
  },
  'gratin-dauphinois': {
    hero: require('../../assets/recipes/gratin-dauphinois.jpg'),
    thumb: require('../../assets/recipes/gratin-dauphinois-thumb.jpg'),
  },
  'gravlax': {
    hero: require('../../assets/recipes/gravlax.jpg'),
    thumb: require('../../assets/recipes/gravlax-thumb.jpg'),
  },
  'greek-salad': {
    hero: require('../../assets/recipes/greek-salad.jpg'),
    thumb: require('../../assets/recipes/greek-salad-thumb.jpg'),
  },
  'green-curry': {
    hero: require('../../assets/recipes/green-curry.jpg'),
    thumb: require('../../assets/recipes/green-curry-thumb.jpg'),
  },
  'green-eggs-and-ham': {
    hero: require('../../assets/recipes/green-eggs-and-ham.jpg'),
    thumb: require('../../assets/recipes/green-eggs-and-ham-thumb.jpg'),
  },
  'grilled-aubergine': {
    hero: require('../../assets/recipes/grilled-aubergine.jpg'),
    thumb: require('../../assets/recipes/grilled-aubergine-thumb.jpg'),
  },
  'grilled-cheese': {
    hero: require('../../assets/recipes/grilled-cheese.jpg'),
    thumb: require('../../assets/recipes/grilled-cheese-thumb.jpg'),
  },
  'guacamole': {
    hero: require('../../assets/recipes/guacamole.jpg'),
    thumb: require('../../assets/recipes/guacamole-thumb.jpg'),
  },
  'gunkanmaki': {
    hero: require('../../assets/recipes/gunkanmaki.jpg'),
    thumb: require('../../assets/recipes/gunkanmaki-thumb.jpg'),
  },
  'gyoza': {
    hero: require('../../assets/recipes/gyoza.jpg'),
    thumb: require('../../assets/recipes/gyoza-thumb.jpg'),
  },
  'gyudon': {
    hero: require('../../assets/recipes/gyudon.jpg'),
    thumb: require('../../assets/recipes/gyudon-thumb.jpg'),
  },
  'hachee': {
    hero: require('../../assets/recipes/hachee.jpg'),
    thumb: require('../../assets/recipes/hachee-thumb.jpg'),
  },
  'haggis': {
    hero: require('../../assets/recipes/haggis.jpg'),
    thumb: require('../../assets/recipes/haggis-thumb.jpg'),
  },
  'hallaca': {
    hero: require('../../assets/recipes/hallaca.jpg'),
    thumb: require('../../assets/recipes/hallaca-thumb.jpg'),
  },
  'halo-halo': {
    hero: require('../../assets/recipes/halo-halo.jpg'),
    thumb: require('../../assets/recipes/halo-halo-thumb.jpg'),
  },
  'halva': {
    hero: require('../../assets/recipes/halva.jpg'),
    thumb: require('../../assets/recipes/halva-thumb.jpg'),
  },
  'haupia': {
    hero: require('../../assets/recipes/haupia.jpg'),
    thumb: require('../../assets/recipes/haupia-thumb.jpg'),
  },
  'henry-thiele-s-pancake': {
    hero: require('../../assets/recipes/henry-thiele-s-pancake.jpg'),
    thumb: require('../../assets/recipes/henry-thiele-s-pancake-thumb.jpg'),
  },
  'homemade-tempeh': {
    hero: require('../../assets/recipes/homemade-tempeh.jpg'),
    thumb: require('../../assets/recipes/homemade-tempeh-thumb.jpg'),
  },
  'homemade-wheat-tortillas': {
    hero: require('../../assets/recipes/homemade-wheat-tortillas.jpg'),
    thumb: require('../../assets/recipes/homemade-wheat-tortillas-thumb.jpg'),
  },
  'hominy-grits': {
    hero: require('../../assets/recipes/hominy-grits.jpg'),
    thumb: require('../../assets/recipes/hominy-grits-thumb.jpg'),
  },
  'hoppin-john': {
    hero: require('../../assets/recipes/hoppin-john.jpg'),
    thumb: require('../../assets/recipes/hoppin-john-thumb.jpg'),
  },
  'hot-and-sour-soup': {
    hero: require('../../assets/recipes/hot-and-sour-soup.jpg'),
    thumb: require('../../assets/recipes/hot-and-sour-soup-thumb.jpg'),
  },
  'huevos-rancheros': {
    hero: require('../../assets/recipes/huevos-rancheros.jpg'),
    thumb: require('../../assets/recipes/huevos-rancheros-thumb.jpg'),
  },
  'hummus': {
    hero: require('../../assets/recipes/hummus.jpg'),
    thumb: require('../../assets/recipes/hummus-thumb.jpg'),
  },
  'hush-puppies': {
    hero: require('../../assets/recipes/hush-puppies.jpg'),
    thumb: require('../../assets/recipes/hush-puppies-thumb.jpg'),
  },
  'ifisashi': {
    hero: require('../../assets/recipes/ifisashi.jpg'),
    thumb: require('../../assets/recipes/ifisashi-thumb.jpg'),
  },
  'inarizushi': {
    hero: require('../../assets/recipes/inarizushi.jpg'),
    thumb: require('../../assets/recipes/inarizushi-thumb.jpg'),
  },
  'indian-butter-chicken': {
    hero: require('../../assets/recipes/indian-butter-chicken.jpg'),
    thumb: require('../../assets/recipes/indian-butter-chicken-thumb.jpg'),
  },
  'indian-hard-tack': {
    hero: require('../../assets/recipes/indian-hard-tack.jpg'),
    thumb: require('../../assets/recipes/indian-hard-tack-thumb.jpg'),
  },
  'injera': {
    hero: require('../../assets/recipes/injera.jpg'),
    thumb: require('../../assets/recipes/injera-thumb.jpg'),
  },
  'israeli-salad': {
    hero: require('../../assets/recipes/israeli-salad.jpg'),
    thumb: require('../../assets/recipes/israeli-salad-thumb.jpg'),
  },
  'jalapeno-sausage-and-bacon-appetizers': {
    hero: require('../../assets/recipes/jalapeno-sausage-and-bacon-appetizers.jpg'),
    thumb: require('../../assets/recipes/jalapeno-sausage-and-bacon-appetizers-thumb.jpg'),
  },
  'jamaican-jerk-chicken': {
    hero: require('../../assets/recipes/jamaican-jerk-chicken.jpg'),
    thumb: require('../../assets/recipes/jamaican-jerk-chicken-thumb.jpg'),
  },
  'jambalaya': {
    hero: require('../../assets/recipes/jambalaya.jpg'),
    thumb: require('../../assets/recipes/jambalaya-thumb.jpg'),
  },
  'japanese-curry': {
    hero: require('../../assets/recipes/japanese-curry.jpg'),
    thumb: require('../../assets/recipes/japanese-curry-thumb.jpg'),
  },
  'jollof-rice': {
    hero: require('../../assets/recipes/jollof-rice.jpg'),
    thumb: require('../../assets/recipes/jollof-rice-thumb.jpg'),
  },
  'ka-ak': {
    hero: require('../../assets/recipes/ka-ak.jpg'),
    thumb: require('../../assets/recipes/ka-ak-thumb.jpg'),
  },
  'kabab-barg': {
    hero: require('../../assets/recipes/kabab-barg.jpg'),
    thumb: require('../../assets/recipes/kabab-barg-thumb.jpg'),
  },
  'kanafeh': {
    hero: require('../../assets/recipes/kanafeh.jpg'),
    thumb: require('../../assets/recipes/kanafeh-thumb.jpg'),
  },
  'karaage': {
    hero: require('../../assets/recipes/karaage.jpg'),
    thumb: require('../../assets/recipes/karaage-thumb.jpg'),
  },
  'kare-kare': {
    hero: require('../../assets/recipes/kare-kare.jpg'),
    thumb: require('../../assets/recipes/kare-kare-thumb.jpg'),
  },
  'karelian-pasties': {
    hero: require('../../assets/recipes/karelian-pasties.jpg'),
    thumb: require('../../assets/recipes/karelian-pasties-thumb.jpg'),
  },
  'kari-ayam': {
    hero: require('../../assets/recipes/kari-ayam.jpg'),
    thumb: require('../../assets/recipes/kari-ayam-thumb.jpg'),
  },
  'kasnocken': {
    hero: require('../../assets/recipes/kasnocken.jpg'),
    thumb: require('../../assets/recipes/kasnocken-thumb.jpg'),
  },
  'kedgeree': {
    hero: require('../../assets/recipes/kedgeree.jpg'),
    thumb: require('../../assets/recipes/kedgeree-thumb.jpg'),
  },
  'kesra': {
    hero: require('../../assets/recipes/kesra.jpg'),
    thumb: require('../../assets/recipes/kesra-thumb.jpg'),
  },
  'kitfo': {
    hero: require('../../assets/recipes/kitfo.jpg'),
    thumb: require('../../assets/recipes/kitfo-thumb.jpg'),
  },
  'koesisters-with-coconut': {
    hero: require('../../assets/recipes/koesisters-with-coconut.jpg'),
    thumb: require('../../assets/recipes/koesisters-with-coconut-thumb.jpg'),
  },
  'kubaneh': {
    hero: require('../../assets/recipes/kubaneh.jpg'),
    thumb: require('../../assets/recipes/kubaneh-thumb.jpg'),
  },
  'kuih-lapis': {
    hero: require('../../assets/recipes/kuih-lapis.jpg'),
    thumb: require('../../assets/recipes/kuih-lapis-thumb.jpg'),
  },
  'kung-pao-chicken': {
    hero: require('../../assets/recipes/kung-pao-chicken.jpg'),
    thumb: require('../../assets/recipes/kung-pao-chicken-thumb.jpg'),
  },
  'kwek-kwek': {
    hero: require('../../assets/recipes/kwek-kwek.jpg'),
    thumb: require('../../assets/recipes/kwek-kwek-thumb.jpg'),
  },
  'kyopulo': {
    hero: require('../../assets/recipes/kyopulo.jpg'),
    thumb: require('../../assets/recipes/kyopulo-thumb.jpg'),
  },
  'kyselo': {
    hero: require('../../assets/recipes/kyselo.jpg'),
    thumb: require('../../assets/recipes/kyselo-thumb.jpg'),
  },
  'lady-finger-cookies': {
    hero: require('../../assets/recipes/lady-finger-cookies.jpg'),
    thumb: require('../../assets/recipes/lady-finger-cookies-thumb.jpg'),
  },
  'lahoh': {
    hero: require('../../assets/recipes/lahoh.jpg'),
    thumb: require('../../assets/recipes/lahoh-thumb.jpg'),
  },
  'lancashire-corned-beef-hash': {
    hero: require('../../assets/recipes/lancashire-corned-beef-hash.jpg'),
    thumb: require('../../assets/recipes/lancashire-corned-beef-hash-thumb.jpg'),
  },
  'lancashire-hotpot': {
    hero: require('../../assets/recipes/lancashire-hotpot.jpg'),
    thumb: require('../../assets/recipes/lancashire-hotpot-thumb.jpg'),
  },
  'langos': {
    hero: require('../../assets/recipes/langos.jpg'),
    thumb: require('../../assets/recipes/langos-thumb.jpg'),
  },
  'lapis-legit': {
    hero: require('../../assets/recipes/lapis-legit.jpg'),
    thumb: require('../../assets/recipes/lapis-legit-thumb.jpg'),
  },
  'lasagne': {
    hero: require('../../assets/recipes/lasagne.jpg'),
    thumb: require('../../assets/recipes/lasagne-thumb.jpg'),
  },
  'latino-scramble': {
    hero: require('../../assets/recipes/latino-scramble.jpg'),
    thumb: require('../../assets/recipes/latino-scramble-thumb.jpg'),
  },
  'le-tourin': {
    hero: require('../../assets/recipes/le-tourin.jpg'),
    thumb: require('../../assets/recipes/le-tourin-thumb.jpg'),
  },
  'lefse': {
    hero: require('../../assets/recipes/lefse.jpg'),
    thumb: require('../../assets/recipes/lefse-thumb.jpg'),
  },
  'lemon-meringue-pie': {
    hero: require('../../assets/recipes/lemon-meringue-pie.jpg'),
    thumb: require('../../assets/recipes/lemon-meringue-pie-thumb.jpg'),
  },
  'lemon-mille-feuille': {
    hero: require('../../assets/recipes/lemon-mille-feuille.jpg'),
    thumb: require('../../assets/recipes/lemon-mille-feuille-thumb.jpg'),
  },
  'lemon-squares': {
    hero: require('../../assets/recipes/lemon-squares.jpg'),
    thumb: require('../../assets/recipes/lemon-squares-thumb.jpg'),
  },
  'limoncello': {
    hero: require('../../assets/recipes/limoncello.jpg'),
    thumb: require('../../assets/recipes/limoncello-thumb.jpg'),
  },
  'liverpool-lamb-and-vegetable-soup': {
    hero: require('../../assets/recipes/liverpool-lamb-and-vegetable-soup.jpg'),
    thumb: require('../../assets/recipes/liverpool-lamb-and-vegetable-soup-thumb.jpg'),
  },
  'lo-mein': {
    hero: require('../../assets/recipes/lo-mein.jpg'),
    thumb: require('../../assets/recipes/lo-mein-thumb.jpg'),
  },
  'lobster-thermidor': {
    hero: require('../../assets/recipes/lobster-thermidor.jpg'),
    thumb: require('../../assets/recipes/lobster-thermidor-thumb.jpg'),
  },
  'loco-moco': {
    hero: require('../../assets/recipes/loco-moco.jpg'),
    thumb: require('../../assets/recipes/loco-moco-thumb.jpg'),
  },
  'lolly-cake': {
    hero: require('../../assets/recipes/lolly-cake.jpg'),
    thumb: require('../../assets/recipes/lolly-cake-thumb.jpg'),
  },
  'lomo-saltado': {
    hero: require('../../assets/recipes/lomo-saltado.jpg'),
    thumb: require('../../assets/recipes/lomo-saltado-thumb.jpg'),
  },
  'loukoumas': {
    hero: require('../../assets/recipes/loukoumas.jpg'),
    thumb: require('../../assets/recipes/loukoumas-thumb.jpg'),
  },
  'luciabullar': {
    hero: require('../../assets/recipes/luciabullar.jpg'),
    thumb: require('../../assets/recipes/luciabullar-thumb.jpg'),
  },
  'lumberjacks': {
    hero: require('../../assets/recipes/lumberjacks.jpg'),
    thumb: require('../../assets/recipes/lumberjacks-thumb.jpg'),
  },
  'lumpiang-shanghai': {
    hero: require('../../assets/recipes/lumpiang-shanghai.jpg'),
    thumb: require('../../assets/recipes/lumpiang-shanghai-thumb.jpg'),
  },
  'm-semen': {
    hero: require('../../assets/recipes/m-semen.jpg'),
    thumb: require('../../assets/recipes/m-semen-thumb.jpg'),
  },
  'mac-and-cheese': {
    hero: require('../../assets/recipes/mac-and-cheese.jpg'),
    thumb: require('../../assets/recipes/mac-and-cheese-thumb.jpg'),
  },
  'machacado-con-huevo': {
    hero: require('../../assets/recipes/machacado-con-huevo.jpg'),
    thumb: require('../../assets/recipes/machacado-con-huevo-thumb.jpg'),
  },
  'maja-blanca': {
    hero: require('../../assets/recipes/maja-blanca.jpg'),
    thumb: require('../../assets/recipes/maja-blanca-thumb.jpg'),
  },
  'makizushi': {
    hero: require('../../assets/recipes/makizushi.jpg'),
    thumb: require('../../assets/recipes/makizushi-thumb.jpg'),
  },
  'malawach': {
    hero: require('../../assets/recipes/malawach.jpg'),
    thumb: require('../../assets/recipes/malawach-thumb.jpg'),
  },
  'malvani-chicken-curry': {
    hero: require('../../assets/recipes/malvani-chicken-curry.jpg'),
    thumb: require('../../assets/recipes/malvani-chicken-curry-thumb.jpg'),
  },
  'manhattan-clam-chowder': {
    hero: require('../../assets/recipes/manhattan-clam-chowder.jpg'),
    thumb: require('../../assets/recipes/manhattan-clam-chowder-thumb.jpg'),
  },
  'mapo-tofu': {
    hero: require('../../assets/recipes/mapo-tofu.jpg'),
    thumb: require('../../assets/recipes/mapo-tofu-thumb.jpg'),
  },
  'marshmallows': {
    hero: require('../../assets/recipes/marshmallows.jpg'),
    thumb: require('../../assets/recipes/marshmallows-thumb.jpg'),
  },
  'masa': {
    hero: require('../../assets/recipes/masa.jpg'),
    thumb: require('../../assets/recipes/masa-thumb.jpg'),
  },
  'matar-paneer': {
    hero: require('../../assets/recipes/matar-paneer.jpg'),
    thumb: require('../../assets/recipes/matar-paneer-thumb.jpg'),
  },
  'mato-de-pedralbes': {
    hero: require('../../assets/recipes/mato-de-pedralbes.jpg'),
    thumb: require('../../assets/recipes/mato-de-pedralbes-thumb.jpg'),
  },
  'mazorca-desgranada': {
    hero: require('../../assets/recipes/mazorca-desgranada.jpg'),
    thumb: require('../../assets/recipes/mazorca-desgranada-thumb.jpg'),
  },
  'meat-and-shrimp-potstickers': {
    hero: require('../../assets/recipes/meat-and-shrimp-potstickers.jpg'),
    thumb: require('../../assets/recipes/meat-and-shrimp-potstickers-thumb.jpg'),
  },
  'meatballs': {
    hero: require('../../assets/recipes/meatballs.jpg'),
    thumb: require('../../assets/recipes/meatballs-thumb.jpg'),
  },
  'meatloaf': {
    hero: require('../../assets/recipes/meatloaf.jpg'),
    thumb: require('../../assets/recipes/meatloaf-thumb.jpg'),
  },
  'mediterranean-grilled-tuna': {
    hero: require('../../assets/recipes/mediterranean-grilled-tuna.jpg'),
    thumb: require('../../assets/recipes/mediterranean-grilled-tuna-thumb.jpg'),
  },
  'menudo': {
    hero: require('../../assets/recipes/menudo.jpg'),
    thumb: require('../../assets/recipes/menudo-thumb.jpg'),
  },
  'mhadjeb': {
    hero: require('../../assets/recipes/mhadjeb.jpg'),
    thumb: require('../../assets/recipes/mhadjeb-thumb.jpg'),
  },
  'minestra': {
    hero: require('../../assets/recipes/minestra.jpg'),
    thumb: require('../../assets/recipes/minestra-thumb.jpg'),
  },
  'minestrone': {
    hero: require('../../assets/recipes/minestrone.jpg'),
    thumb: require('../../assets/recipes/minestrone-thumb.jpg'),
  },
  'miso-soup': {
    hero: require('../../assets/recipes/miso-soup.jpg'),
    thumb: require('../../assets/recipes/miso-soup-thumb.jpg'),
  },
  'monkey-bread': {
    hero: require('../../assets/recipes/monkey-bread.jpg'),
    thumb: require('../../assets/recipes/monkey-bread-thumb.jpg'),
  },
  'moules-mariniere': {
    hero: require('../../assets/recipes/moules-mariniere.jpg'),
    thumb: require('../../assets/recipes/moules-mariniere-thumb.jpg'),
  },
  'moussaka': {
    hero: require('../../assets/recipes/moussaka.jpg'),
    thumb: require('../../assets/recipes/moussaka-thumb.jpg'),
  },
  'msemmen': {
    hero: require('../../assets/recipes/msemmen.jpg'),
    thumb: require('../../assets/recipes/msemmen-thumb.jpg'),
  },
  'mukimo': {
    hero: require('../../assets/recipes/mukimo.jpg'),
    thumb: require('../../assets/recipes/mukimo-thumb.jpg'),
  },
  'mushy-peas': {
    hero: require('../../assets/recipes/mushy-peas.jpg'),
    thumb: require('../../assets/recipes/mushy-peas-thumb.jpg'),
  },
  'naan': {
    hero: require('../../assets/recipes/naan.jpg'),
    thumb: require('../../assets/recipes/naan-thumb.jpg'),
  },
  'nachos': {
    hero: require('../../assets/recipes/nachos.jpg'),
    thumb: require('../../assets/recipes/nachos-thumb.jpg'),
  },
  'nanaimo-bars': {
    hero: require('../../assets/recipes/nanaimo-bars.jpg'),
    thumb: require('../../assets/recipes/nanaimo-bars-thumb.jpg'),
  },
  'ndole': {
    hero: require('../../assets/recipes/ndole.jpg'),
    thumb: require('../../assets/recipes/ndole-thumb.jpg'),
  },
  'new-england-potato-salad': {
    hero: require('../../assets/recipes/new-england-potato-salad.jpg'),
    thumb: require('../../assets/recipes/new-england-potato-salad-thumb.jpg'),
  },
  'nilagang-baka': {
    hero: require('../../assets/recipes/nilagang-baka.jpg'),
    thumb: require('../../assets/recipes/nilagang-baka-thumb.jpg'),
  },
  'no-knead-bread': {
    hero: require('../../assets/recipes/no-knead-bread.jpg'),
    thumb: require('../../assets/recipes/no-knead-bread-thumb.jpg'),
  },
  'nuremberg-gingerbread': {
    hero: require('../../assets/recipes/nuremberg-gingerbread.jpg'),
    thumb: require('../../assets/recipes/nuremberg-gingerbread-thumb.jpg'),
  },
  'okonomiyaki': {
    hero: require('../../assets/recipes/okonomiyaki.jpg'),
    thumb: require('../../assets/recipes/okonomiyaki-thumb.jpg'),
  },
  'omelette-of-breadcrumbs': {
    hero: require('../../assets/recipes/omelette-of-breadcrumbs.jpg'),
    thumb: require('../../assets/recipes/omelette-of-breadcrumbs-thumb.jpg'),
  },
  'onigiri': {
    hero: require('../../assets/recipes/onigiri.jpg'),
    thumb: require('../../assets/recipes/onigiri-thumb.jpg'),
  },
  'onion-rings': {
    hero: require('../../assets/recipes/onion-rings.jpg'),
    thumb: require('../../assets/recipes/onion-rings-thumb.jpg'),
  },
  'ossobuco-alla-milanese': {
    hero: require('../../assets/recipes/ossobuco-alla-milanese.jpg'),
    thumb: require('../../assets/recipes/ossobuco-alla-milanese-thumb.jpg'),
  },
  'oyakodon': {
    hero: require('../../assets/recipes/oyakodon.jpg'),
    thumb: require('../../assets/recipes/oyakodon-thumb.jpg'),
  },
  'pad-thai': {
    hero: require('../../assets/recipes/pad-thai.jpg'),
    thumb: require('../../assets/recipes/pad-thai-thumb.jpg'),
  },
  'paella': {
    hero: require('../../assets/recipes/paella.jpg'),
    thumb: require('../../assets/recipes/paella-thumb.jpg'),
  },
  'paella-de-marisco': {
    hero: require('../../assets/recipes/paella-de-marisco.jpg'),
    thumb: require('../../assets/recipes/paella-de-marisco-thumb.jpg'),
  },
  'paella-roja': {
    hero: require('../../assets/recipes/paella-roja.jpg'),
    thumb: require('../../assets/recipes/paella-roja-thumb.jpg'),
  },
  'pain-au-levain-naturel': {
    hero: require('../../assets/recipes/pain-au-levain-naturel.jpg'),
    thumb: require('../../assets/recipes/pain-au-levain-naturel-thumb.jpg'),
  },
  'palatschinken': {
    hero: require('../../assets/recipes/palatschinken.jpg'),
    thumb: require('../../assets/recipes/palatschinken-thumb.jpg'),
  },
  'pan-con-tomate': {
    hero: require('../../assets/recipes/pan-con-tomate.jpg'),
    thumb: require('../../assets/recipes/pan-con-tomate-thumb.jpg'),
  },
  'pancakes': {
    hero: require('../../assets/recipes/pancakes.jpg'),
    thumb: require('../../assets/recipes/pancakes-thumb.jpg'),
  },
  'panna-cotta': {
    hero: require('../../assets/recipes/panna-cotta.jpg'),
    thumb: require('../../assets/recipes/panna-cotta-thumb.jpg'),
  },
  'panocha': {
    hero: require('../../assets/recipes/panocha.jpg'),
    thumb: require('../../assets/recipes/panocha-thumb.jpg'),
  },
  'paprika-chicken': {
    hero: require('../../assets/recipes/paprika-chicken.jpg'),
    thumb: require('../../assets/recipes/paprika-chicken-thumb.jpg'),
  },
  'pasta-casserole': {
    hero: require('../../assets/recipes/pasta-casserole.jpg'),
    thumb: require('../../assets/recipes/pasta-casserole-thumb.jpg'),
  },
  'pastry-for-cornish-pasties': {
    hero: require('../../assets/recipes/pastry-for-cornish-pasties.jpg'),
    thumb: require('../../assets/recipes/pastry-for-cornish-pasties-thumb.jpg'),
  },
  'patatas-bravas': {
    hero: require('../../assets/recipes/patatas-bravas.jpg'),
    thumb: require('../../assets/recipes/patatas-bravas-thumb.jpg'),
  },
  'pavlova': {
    hero: require('../../assets/recipes/pavlova.jpg'),
    thumb: require('../../assets/recipes/pavlova-thumb.jpg'),
  },
  'pecan-pie': {
    hero: require('../../assets/recipes/pecan-pie.jpg'),
    thumb: require('../../assets/recipes/pecan-pie-thumb.jpg'),
  },
  'pesto-genovese': {
    hero: require('../../assets/recipes/pesto-genovese.jpg'),
    thumb: require('../../assets/recipes/pesto-genovese-thumb.jpg'),
  },
  'philly-cheesesteak': {
    hero: require('../../assets/recipes/philly-cheesesteak.jpg'),
    thumb: require('../../assets/recipes/philly-cheesesteak-thumb.jpg'),
  },
  'pho': {
    hero: require('../../assets/recipes/pho.jpg'),
    thumb: require('../../assets/recipes/pho-thumb.jpg'),
  },
  'piadina': {
    hero: require('../../assets/recipes/piadina.jpg'),
    thumb: require('../../assets/recipes/piadina-thumb.jpg'),
  },
  'picadillo': {
    hero: require('../../assets/recipes/picadillo.jpg'),
    thumb: require('../../assets/recipes/picadillo-thumb.jpg'),
  },
  'pierogi': {
    hero: require('../../assets/recipes/pierogi.jpg'),
    thumb: require('../../assets/recipes/pierogi-thumb.jpg'),
  },
  'pigeon-pea-and-fenugreek-curry': {
    hero: require('../../assets/recipes/pigeon-pea-and-fenugreek-curry.jpg'),
    thumb: require('../../assets/recipes/pigeon-pea-and-fenugreek-curry-thumb.jpg'),
  },
  'pita': {
    hero: require('../../assets/recipes/pita.jpg'),
    thumb: require('../../assets/recipes/pita-thumb.jpg'),
  },
  'pizza-margherita': {
    hero: require('../../assets/recipes/pizza-margherita.jpg'),
    thumb: require('../../assets/recipes/pizza-margherita-thumb.jpg'),
  },
  'pizza-vanegas': {
    hero: require('../../assets/recipes/pizza-vanegas.jpg'),
    thumb: require('../../assets/recipes/pizza-vanegas-thumb.jpg'),
  },
  'po-boy': {
    hero: require('../../assets/recipes/po-boy.jpg'),
    thumb: require('../../assets/recipes/po-boy-thumb.jpg'),
  },
  'pohe': {
    hero: require('../../assets/recipes/pohe.jpg'),
    thumb: require('../../assets/recipes/pohe-thumb.jpg'),
  },
  'poke-bowl': {
    hero: require('../../assets/recipes/poke-bowl.jpg'),
    thumb: require('../../assets/recipes/poke-bowl-thumb.jpg'),
  },
  'polish-doughnuts': {
    hero: require('../../assets/recipes/polish-doughnuts.jpg'),
    thumb: require('../../assets/recipes/polish-doughnuts-thumb.jpg'),
  },
  'polvorones': {
    hero: require('../../assets/recipes/polvorones.jpg'),
    thumb: require('../../assets/recipes/polvorones-thumb.jpg'),
  },
  'pork-gyoza': {
    hero: require('../../assets/recipes/pork-gyoza.jpg'),
    thumb: require('../../assets/recipes/pork-gyoza-thumb.jpg'),
  },
  'porridge': {
    hero: require('../../assets/recipes/porridge.jpg'),
    thumb: require('../../assets/recipes/porridge-thumb.jpg'),
  },
  'pot-au-feu': {
    hero: require('../../assets/recipes/pot-au-feu.jpg'),
    thumb: require('../../assets/recipes/pot-au-feu-thumb.jpg'),
  },
  'potage-parmentier': {
    hero: require('../../assets/recipes/potage-parmentier.jpg'),
    thumb: require('../../assets/recipes/potage-parmentier-thumb.jpg'),
  },
  'potato-and-cauliflower-curry': {
    hero: require('../../assets/recipes/potato-and-cauliflower-curry.jpg'),
    thumb: require('../../assets/recipes/potato-and-cauliflower-curry-thumb.jpg'),
  },
  'potato-and-sausage-casserole': {
    hero: require('../../assets/recipes/potato-and-sausage-casserole.jpg'),
    thumb: require('../../assets/recipes/potato-and-sausage-casserole-thumb.jpg'),
  },
  'potato-candy-pinwheel': {
    hero: require('../../assets/recipes/potato-candy-pinwheel.jpg'),
    thumb: require('../../assets/recipes/potato-candy-pinwheel-thumb.jpg'),
  },
  'potato-casserole': {
    hero: require('../../assets/recipes/potato-casserole.jpg'),
    thumb: require('../../assets/recipes/potato-casserole-thumb.jpg'),
  },
  'potato-curry': {
    hero: require('../../assets/recipes/potato-curry.jpg'),
    thumb: require('../../assets/recipes/potato-curry-thumb.jpg'),
  },
  'potato-gratin': {
    hero: require('../../assets/recipes/potato-gratin.jpg'),
    thumb: require('../../assets/recipes/potato-gratin-thumb.jpg'),
  },
  'potato-salad': {
    hero: require('../../assets/recipes/potato-salad.jpg'),
    thumb: require('../../assets/recipes/potato-salad-thumb.jpg'),
  },
  'potato-samosas': {
    hero: require('../../assets/recipes/potato-samosas.jpg'),
    thumb: require('../../assets/recipes/potato-samosas-thumb.jpg'),
  },
  'potato-soup': {
    hero: require('../../assets/recipes/potato-soup.jpg'),
    thumb: require('../../assets/recipes/potato-soup-thumb.jpg'),
  },
  'poutine': {
    hero: require('../../assets/recipes/poutine.jpg'),
    thumb: require('../../assets/recipes/poutine-thumb.jpg'),
  },
  'pretzels': {
    hero: require('../../assets/recipes/pretzels.jpg'),
    thumb: require('../../assets/recipes/pretzels-thumb.jpg'),
  },
  'pumpkin-pie': {
    hero: require('../../assets/recipes/pumpkin-pie.jpg'),
    thumb: require('../../assets/recipes/pumpkin-pie-thumb.jpg'),
  },
  'pupusas': {
    hero: require('../../assets/recipes/pupusas.jpg'),
    thumb: require('../../assets/recipes/pupusas-thumb.jpg'),
  },
  'puttanesca': {
    hero: require('../../assets/recipes/puttanesca.jpg'),
    thumb: require('../../assets/recipes/puttanesca-thumb.jpg'),
  },
  'queen-of-puddings': {
    hero: require('../../assets/recipes/queen-of-puddings.jpg'),
    thumb: require('../../assets/recipes/queen-of-puddings-thumb.jpg'),
  },
  'quesadilla': {
    hero: require('../../assets/recipes/quesadilla.jpg'),
    thumb: require('../../assets/recipes/quesadilla-thumb.jpg'),
  },
  'quiche-lorraine': {
    hero: require('../../assets/recipes/quiche-lorraine.jpg'),
    thumb: require('../../assets/recipes/quiche-lorraine-thumb.jpg'),
  },
  'ramen': {
    hero: require('../../assets/recipes/ramen.jpg'),
    thumb: require('../../assets/recipes/ramen-thumb.jpg'),
  },
  'ratatouille': {
    hero: require('../../assets/recipes/ratatouille.jpg'),
    thumb: require('../../assets/recipes/ratatouille-thumb.jpg'),
  },
  'ravioli': {
    hero: require('../../assets/recipes/ravioli.jpg'),
    thumb: require('../../assets/recipes/ravioli-thumb.jpg'),
  },
  'reindling': {
    hero: require('../../assets/recipes/reindling.jpg'),
    thumb: require('../../assets/recipes/reindling-thumb.jpg'),
  },
  'reuben-sandwich': {
    hero: require('../../assets/recipes/reuben-sandwich.jpg'),
    thumb: require('../../assets/recipes/reuben-sandwich-thumb.jpg'),
  },
  'rhubarb-crumble': {
    hero: require('../../assets/recipes/rhubarb-crumble.jpg'),
    thumb: require('../../assets/recipes/rhubarb-crumble-thumb.jpg'),
  },
  'rhubarb-fool': {
    hero: require('../../assets/recipes/rhubarb-fool.jpg'),
    thumb: require('../../assets/recipes/rhubarb-fool-thumb.jpg'),
  },
  'rice-and-lentils': {
    hero: require('../../assets/recipes/rice-and-lentils.jpg'),
    thumb: require('../../assets/recipes/rice-and-lentils-thumb.jpg'),
  },
  'rice-pudding': {
    hero: require('../../assets/recipes/rice-pudding.jpg'),
    thumb: require('../../assets/recipes/rice-pudding-thumb.jpg'),
  },
  'rice-tamale': {
    hero: require('../../assets/recipes/rice-tamale.jpg'),
    thumb: require('../../assets/recipes/rice-tamale-thumb.jpg'),
  },
  'risotto': {
    hero: require('../../assets/recipes/risotto.jpg'),
    thumb: require('../../assets/recipes/risotto-thumb.jpg'),
  },
  'risotto-ai-funghi': {
    hero: require('../../assets/recipes/risotto-ai-funghi.jpg'),
    thumb: require('../../assets/recipes/risotto-ai-funghi-thumb.jpg'),
  },
  'risotto-milanese': {
    hero: require('../../assets/recipes/risotto-milanese.jpg'),
    thumb: require('../../assets/recipes/risotto-milanese-thumb.jpg'),
  },
  'roast-beef': {
    hero: require('../../assets/recipes/roast-beef.jpg'),
    thumb: require('../../assets/recipes/roast-beef-thumb.jpg'),
  },
  'roast-turkey-with-stuffing': {
    hero: require('../../assets/recipes/roast-turkey-with-stuffing.jpg'),
    thumb: require('../../assets/recipes/roast-turkey-with-stuffing-thumb.jpg'),
  },
  'rolex': {
    hero: require('../../assets/recipes/rolex.jpg'),
    thumb: require('../../assets/recipes/rolex-thumb.jpg'),
  },
  'ropa-vieja': {
    hero: require('../../assets/recipes/ropa-vieja.jpg'),
    thumb: require('../../assets/recipes/ropa-vieja-thumb.jpg'),
  },
  'russian-style-waffle-cake': {
    hero: require('../../assets/recipes/russian-style-waffle-cake.jpg'),
    thumb: require('../../assets/recipes/russian-style-waffle-cake-thumb.jpg'),
  },
  'sachertorte': {
    hero: require('../../assets/recipes/sachertorte.jpg'),
    thumb: require('../../assets/recipes/sachertorte-thumb.jpg'),
  },
  'salade-nicoise': {
    hero: require('../../assets/recipes/salade-nicoise.jpg'),
    thumb: require('../../assets/recipes/salade-nicoise-thumb.jpg'),
  },
  'salata-de-boeuf': {
    hero: require('../../assets/recipes/salata-de-boeuf.jpg'),
    thumb: require('../../assets/recipes/salata-de-boeuf-thumb.jpg'),
  },
  'salmorejo': {
    hero: require('../../assets/recipes/salmorejo.jpg'),
    thumb: require('../../assets/recipes/salmorejo-thumb.jpg'),
  },
  'salsa': {
    hero: require('../../assets/recipes/salsa.jpg'),
    thumb: require('../../assets/recipes/salsa-thumb.jpg'),
  },
  'salzburger-nockerl': {
    hero: require('../../assets/recipes/salzburger-nockerl.jpg'),
    thumb: require('../../assets/recipes/salzburger-nockerl-thumb.jpg'),
  },
  'sandwich-layer-cake': {
    hero: require('../../assets/recipes/sandwich-layer-cake.jpg'),
    thumb: require('../../assets/recipes/sandwich-layer-cake-thumb.jpg'),
  },
  'sangria': {
    hero: require('../../assets/recipes/sangria.jpg'),
    thumb: require('../../assets/recipes/sangria-thumb.jpg'),
  },
  'schwarzwalder-kirschtorte': {
    hero: require('../../assets/recipes/schwarzwalder-kirschtorte.jpg'),
    thumb: require('../../assets/recipes/schwarzwalder-kirschtorte-thumb.jpg'),
  },
  'scrambled-eggs': {
    hero: require('../../assets/recipes/scrambled-eggs.jpg'),
    thumb: require('../../assets/recipes/scrambled-eggs-thumb.jpg'),
  },
  'seafood-risotto': {
    hero: require('../../assets/recipes/seafood-risotto.jpg'),
    thumb: require('../../assets/recipes/seafood-risotto-thumb.jpg'),
  },
  'shakshuka': {
    hero: require('../../assets/recipes/shakshuka.jpg'),
    thumb: require('../../assets/recipes/shakshuka-thumb.jpg'),
  },
  'shawarma': {
    hero: require('../../assets/recipes/shawarma.jpg'),
    thumb: require('../../assets/recipes/shawarma-thumb.jpg'),
  },
  'shepherds-pie': {
    hero: require('../../assets/recipes/shepherds-pie.jpg'),
    thumb: require('../../assets/recipes/shepherds-pie-thumb.jpg'),
  },
  'shopska-salata': {
    hero: require('../../assets/recipes/shopska-salata.jpg'),
    thumb: require('../../assets/recipes/shopska-salata-thumb.jpg'),
  },
  'simple-spaghetti': {
    hero: require('../../assets/recipes/simple-spaghetti.jpg'),
    thumb: require('../../assets/recipes/simple-spaghetti-thumb.jpg'),
  },
  'simple-tarragon-quiche': {
    hero: require('../../assets/recipes/simple-tarragon-quiche.jpg'),
    thumb: require('../../assets/recipes/simple-tarragon-quiche-thumb.jpg'),
  },
  'sloppy-joes': {
    hero: require('../../assets/recipes/sloppy-joes.jpg'),
    thumb: require('../../assets/recipes/sloppy-joes-thumb.jpg'),
  },
  'snickerdoodles': {
    hero: require('../../assets/recipes/snickerdoodles.jpg'),
    thumb: require('../../assets/recipes/snickerdoodles-thumb.jpg'),
  },
  'soda-bread': {
    hero: require('../../assets/recipes/soda-bread.jpg'),
    thumb: require('../../assets/recipes/soda-bread-thumb.jpg'),
  },
  'soft-sugar-cookies': {
    hero: require('../../assets/recipes/soft-sugar-cookies.jpg'),
    thumb: require('../../assets/recipes/soft-sugar-cookies-thumb.jpg'),
  },
  'sopaipillas': {
    hero: require('../../assets/recipes/sopaipillas.jpg'),
    thumb: require('../../assets/recipes/sopaipillas-thumb.jpg'),
  },
  'soup-joumou': {
    hero: require('../../assets/recipes/soup-joumou.jpg'),
    thumb: require('../../assets/recipes/soup-joumou-thumb.jpg'),
  },
  'spaetzle': {
    hero: require('../../assets/recipes/spaetzle.jpg'),
    thumb: require('../../assets/recipes/spaetzle-thumb.jpg'),
  },
  'spaghetti-with-clams': {
    hero: require('../../assets/recipes/spaghetti-with-clams.jpg'),
    thumb: require('../../assets/recipes/spaghetti-with-clams-thumb.jpg'),
  },
  'spanakopita': {
    hero: require('../../assets/recipes/spanakopita.jpg'),
    thumb: require('../../assets/recipes/spanakopita-thumb.jpg'),
  },
  'spanish-omelet': {
    hero: require('../../assets/recipes/spanish-omelet.jpg'),
    thumb: require('../../assets/recipes/spanish-omelet-thumb.jpg'),
  },
  'speculaas': {
    hero: require('../../assets/recipes/speculaas.jpg'),
    thumb: require('../../assets/recipes/speculaas-thumb.jpg'),
  },
  'sponge-cake': {
    hero: require('../../assets/recipes/sponge-cake.jpg'),
    thumb: require('../../assets/recipes/sponge-cake-thumb.jpg'),
  },
  'spoonbread': {
    hero: require('../../assets/recipes/spoonbread.jpg'),
    thumb: require('../../assets/recipes/spoonbread-thumb.jpg'),
  },
  'springerle': {
    hero: require('../../assets/recipes/springerle.jpg'),
    thumb: require('../../assets/recipes/springerle-thumb.jpg'),
  },
  'spritzgeback': {
    hero: require('../../assets/recipes/spritzgeback.jpg'),
    thumb: require('../../assets/recipes/spritzgeback-thumb.jpg'),
  },
  'steak-and-ale-pie': {
    hero: require('../../assets/recipes/steak-and-ale-pie.jpg'),
    thumb: require('../../assets/recipes/steak-and-ale-pie-thumb.jpg'),
  },
  'steak-au-poivre': {
    hero: require('../../assets/recipes/steak-au-poivre.jpg'),
    thumb: require('../../assets/recipes/steak-au-poivre-thumb.jpg'),
  },
  'steak-tartare': {
    hero: require('../../assets/recipes/steak-tartare.jpg'),
    thumb: require('../../assets/recipes/steak-tartare-thumb.jpg'),
  },
  'steamed-tuna-bao-buns': {
    hero: require('../../assets/recipes/steamed-tuna-bao-buns.jpg'),
    thumb: require('../../assets/recipes/steamed-tuna-bao-buns-thumb.jpg'),
  },
  'stracciatella': {
    hero: require('../../assets/recipes/stracciatella.jpg'),
    thumb: require('../../assets/recipes/stracciatella-thumb.jpg'),
  },
  'strawberry-and-yogurt-eton-mess': {
    hero: require('../../assets/recipes/strawberry-and-yogurt-eton-mess.jpg'),
    thumb: require('../../assets/recipes/strawberry-and-yogurt-eton-mess-thumb.jpg'),
  },
  'strawberry-shortcake': {
    hero: require('../../assets/recipes/strawberry-shortcake.jpg'),
    thumb: require('../../assets/recipes/strawberry-shortcake-thumb.jpg'),
  },
  'stroopwafels': {
    hero: require('../../assets/recipes/stroopwafels.jpg'),
    thumb: require('../../assets/recipes/stroopwafels-thumb.jpg'),
  },
  'struffoli': {
    hero: require('../../assets/recipes/struffoli.jpg'),
    thumb: require('../../assets/recipes/struffoli-thumb.jpg'),
  },
  'stuffed-crabs': {
    hero: require('../../assets/recipes/stuffed-crabs.jpg'),
    thumb: require('../../assets/recipes/stuffed-crabs-thumb.jpg'),
  },
  'stuffed-duck-breast-with-cabbage-and-dumplings': {
    hero: require('../../assets/recipes/stuffed-duck-breast-with-cabbage-and-dumplings.jpg'),
    thumb: require('../../assets/recipes/stuffed-duck-breast-with-cabbage-and-dumplings-thumb.jpg'),
  },
  'stuffed-grape-leaves': {
    hero: require('../../assets/recipes/stuffed-grape-leaves.jpg'),
    thumb: require('../../assets/recipes/stuffed-grape-leaves-thumb.jpg'),
  },
  'stuffed-peppers': {
    hero: require('../../assets/recipes/stuffed-peppers.jpg'),
    thumb: require('../../assets/recipes/stuffed-peppers-thumb.jpg'),
  },
  'sukiyaki': {
    hero: require('../../assets/recipes/sukiyaki.jpg'),
    thumb: require('../../assets/recipes/sukiyaki-thumb.jpg'),
  },
  'summer-pudding': {
    hero: require('../../assets/recipes/summer-pudding.jpg'),
    thumb: require('../../assets/recipes/summer-pudding-thumb.jpg'),
  },
  'szegedin-goulash': {
    hero: require('../../assets/recipes/szegedin-goulash.jpg'),
    thumb: require('../../assets/recipes/szegedin-goulash-thumb.jpg'),
  },
  'tabbouleh': {
    hero: require('../../assets/recipes/tabbouleh.jpg'),
    thumb: require('../../assets/recipes/tabbouleh-thumb.jpg'),
  },
  'tacos-al-pastor': {
    hero: require('../../assets/recipes/tacos-al-pastor.jpg'),
    thumb: require('../../assets/recipes/tacos-al-pastor-thumb.jpg'),
  },
  'tamagoyaki': {
    hero: require('../../assets/recipes/tamagoyaki.jpg'),
    thumb: require('../../assets/recipes/tamagoyaki-thumb.jpg'),
  },
  'tamina': {
    hero: require('../../assets/recipes/tamina.jpg'),
    thumb: require('../../assets/recipes/tamina-thumb.jpg'),
  },
  'tarte-tatin': {
    hero: require('../../assets/recipes/tarte-tatin.jpg'),
    thumb: require('../../assets/recipes/tarte-tatin-thumb.jpg'),
  },
  'tartiflette': {
    hero: require('../../assets/recipes/tartiflette.jpg'),
    thumb: require('../../assets/recipes/tartiflette-thumb.jpg'),
  },
  'tattie-scones': {
    hero: require('../../assets/recipes/tattie-scones.jpg'),
    thumb: require('../../assets/recipes/tattie-scones-thumb.jpg'),
  },
  'tempura': {
    hero: require('../../assets/recipes/tempura.jpg'),
    thumb: require('../../assets/recipes/tempura-thumb.jpg'),
  },
  'tequenos': {
    hero: require('../../assets/recipes/tequenos.jpg'),
    thumb: require('../../assets/recipes/tequenos-thumb.jpg'),
  },
  'teurgoule': {
    hero: require('../../assets/recipes/teurgoule.jpg'),
    thumb: require('../../assets/recipes/teurgoule-thumb.jpg'),
  },
  'tikka-masala': {
    hero: require('../../assets/recipes/tikka-masala.jpg'),
    thumb: require('../../assets/recipes/tikka-masala-thumb.jpg'),
  },
  'tiramisu': {
    hero: require('../../assets/recipes/tiramisu.jpg'),
    thumb: require('../../assets/recipes/tiramisu-thumb.jpg'),
  },
  'tonkatsu': {
    hero: require('../../assets/recipes/tonkatsu.jpg'),
    thumb: require('../../assets/recipes/tonkatsu-thumb.jpg'),
  },
  'tonkotsu-ramen': {
    hero: require('../../assets/recipes/tonkotsu-ramen.jpg'),
    thumb: require('../../assets/recipes/tonkotsu-ramen-thumb.jpg'),
  },
  'tortilla-espanola': {
    hero: require('../../assets/recipes/tortilla-espanola.jpg'),
    thumb: require('../../assets/recipes/tortilla-espanola-thumb.jpg'),
  },
  'traditional-finnish-lemon-mead': {
    hero: require('../../assets/recipes/traditional-finnish-lemon-mead.jpg'),
    thumb: require('../../assets/recipes/traditional-finnish-lemon-mead-thumb.jpg'),
  },
  'tres-leches-cake': {
    hero: require('../../assets/recipes/tres-leches-cake.jpg'),
    thumb: require('../../assets/recipes/tres-leches-cake-thumb.jpg'),
  },
  'trifle': {
    hero: require('../../assets/recipes/trifle.jpg'),
    thumb: require('../../assets/recipes/trifle-thumb.jpg'),
  },
  'tripes-a-la-mode-de-caen': {
    hero: require('../../assets/recipes/tripes-a-la-mode-de-caen.jpg'),
    thumb: require('../../assets/recipes/tripes-a-la-mode-de-caen-thumb.jpg'),
  },
  'tuna-salad': {
    hero: require('../../assets/recipes/tuna-salad.jpg'),
    thumb: require('../../assets/recipes/tuna-salad-thumb.jpg'),
  },
  'turkish-delight': {
    hero: require('../../assets/recipes/turkish-delight.jpg'),
    thumb: require('../../assets/recipes/turkish-delight-thumb.jpg'),
  },
  'twice-baked-potatoes': {
    hero: require('../../assets/recipes/twice-baked-potatoes.jpg'),
    thumb: require('../../assets/recipes/twice-baked-potatoes-thumb.jpg'),
  },
  'tzatziki': {
    hero: require('../../assets/recipes/tzatziki.jpg'),
    thumb: require('../../assets/recipes/tzatziki-thumb.jpg'),
  },
  'ume-shu': {
    hero: require('../../assets/recipes/ume-shu.jpg'),
    thumb: require('../../assets/recipes/ume-shu-thumb.jpg'),
  },
  'valencian-inspired-paella': {
    hero: require('../../assets/recipes/valencian-inspired-paella.jpg'),
    thumb: require('../../assets/recipes/valencian-inspired-paella-thumb.jpg'),
  },
  'vanilla-fudge': {
    hero: require('../../assets/recipes/vanilla-fudge.jpg'),
    thumb: require('../../assets/recipes/vanilla-fudge-thumb.jpg'),
  },
  'vanillekipferl': {
    hero: require('../../assets/recipes/vanillekipferl.jpg'),
    thumb: require('../../assets/recipes/vanillekipferl-thumb.jpg'),
  },
  'vegemite-sandwich': {
    hero: require('../../assets/recipes/vegemite-sandwich.jpg'),
    thumb: require('../../assets/recipes/vegemite-sandwich-thumb.jpg'),
  },
  'waffles': {
    hero: require('../../assets/recipes/waffles.jpg'),
    thumb: require('../../assets/recipes/waffles-thumb.jpg'),
  },
  'wakeup-sausage-casserole': {
    hero: require('../../assets/recipes/wakeup-sausage-casserole.jpg'),
    thumb: require('../../assets/recipes/wakeup-sausage-casserole-thumb.jpg'),
  },
  'waldorf-salad': {
    hero: require('../../assets/recipes/waldorf-salad.jpg'),
    thumb: require('../../assets/recipes/waldorf-salad-thumb.jpg'),
  },
  'welsh-fruit-bread': {
    hero: require('../../assets/recipes/welsh-fruit-bread.jpg'),
    thumb: require('../../assets/recipes/welsh-fruit-bread-thumb.jpg'),
  },
  'welsh-rarebit': {
    hero: require('../../assets/recipes/welsh-rarebit.jpg'),
    thumb: require('../../assets/recipes/welsh-rarebit-thumb.jpg'),
  },
  'white-fish-ceviche': {
    hero: require('../../assets/recipes/white-fish-ceviche.jpg'),
    thumb: require('../../assets/recipes/white-fish-ceviche-thumb.jpg'),
  },
  'white-house-honey-ale': {
    hero: require('../../assets/recipes/white-house-honey-ale.jpg'),
    thumb: require('../../assets/recipes/white-house-honey-ale-thumb.jpg'),
  },
  'yakitori': {
    hero: require('../../assets/recipes/yakitori.jpg'),
    thumb: require('../../assets/recipes/yakitori-thumb.jpg'),
  },
  'yeasted-vanilla-sponge-cake': {
    hero: require('../../assets/recipes/yeasted-vanilla-sponge-cake.jpg'),
    thumb: require('../../assets/recipes/yeasted-vanilla-sponge-cake-thumb.jpg'),
  },
  'yeung-chow-fried-rice': {
    hero: require('../../assets/recipes/yeung-chow-fried-rice.jpg'),
    thumb: require('../../assets/recipes/yeung-chow-fried-rice-thumb.jpg'),
  },
  'yubeshi': {
    hero: require('../../assets/recipes/yubeshi.jpg'),
    thumb: require('../../assets/recipes/yubeshi-thumb.jpg'),
  },
  'zacusca': {
    hero: require('../../assets/recipes/zacusca.jpg'),
    thumb: require('../../assets/recipes/zacusca-thumb.jpg'),
  },
  'zippuli': {
    hero: require('../../assets/recipes/zippuli.jpg'),
    thumb: require('../../assets/recipes/zippuli-thumb.jpg'),
  },
  'zupa-ogorkowa': {
    hero: require('../../assets/recipes/zupa-ogorkowa.jpg'),
    thumb: require('../../assets/recipes/zupa-ogorkowa-thumb.jpg'),
  },
};

/** The photograph for a recipe, or null if the slug is not in the library. */
export function recipeImage(slug: string): RecipeImageAssets | null {
  return recipeImages[slug] ?? null;
}
