/**
 * Every dish photograph, as a Metro asset.
 *
 * Generated by scripts/fetch_recipe_images.py - do not edit.
 *
 * Metro resolves `require` at build time from a string literal, so a bundled
 * image cannot be looked up by a path assembled at runtime. That is the whole
 * reason this file is written out rather than computed: one literal per
 * asset, so the bundler can see them all.
 *
 * Two sizes. `hero` is 1000x600 for the recipe screen; `thumb` is a 240x240
 * square for the plan list, where a dozen can be on screen at once and
 * decoding a dozen full-size photographs is how a list starts dropping
 * frames.
 */

import type { ImageSourcePropType } from 'react-native';

export interface RecipeImageAssets {
  hero: ImageSourcePropType;
  thumb: ImageSourcePropType;
}

export const recipeImages: Record<string, RecipeImageAssets> = {
  'aglio-e-olio': {
    hero: require('../../assets/recipes/aglio-e-olio.jpg'),
    thumb: require('../../assets/recipes/aglio-e-olio-thumb.jpg'),
  },
  'albondigas': {
    hero: require('../../assets/recipes/albondigas.jpg'),
    thumb: require('../../assets/recipes/albondigas-thumb.jpg'),
  },
  'banh-mi': {
    hero: require('../../assets/recipes/banh-mi.jpg'),
    thumb: require('../../assets/recipes/banh-mi-thumb.jpg'),
  },
  'bbq-ribs': {
    hero: require('../../assets/recipes/bbq-ribs.jpg'),
    thumb: require('../../assets/recipes/bbq-ribs-thumb.jpg'),
  },
  'beef-bourguignon': {
    hero: require('../../assets/recipes/beef-bourguignon.jpg'),
    thumb: require('../../assets/recipes/beef-bourguignon-thumb.jpg'),
  },
  'bibimbap': {
    hero: require('../../assets/recipes/bibimbap.jpg'),
    thumb: require('../../assets/recipes/bibimbap-thumb.jpg'),
  },
  'blt': {
    hero: require('../../assets/recipes/blt.jpg'),
    thumb: require('../../assets/recipes/blt-thumb.jpg'),
  },
  'bolognese': {
    hero: require('../../assets/recipes/bolognese.jpg'),
    thumb: require('../../assets/recipes/bolognese-thumb.jpg'),
  },
  'borscht': {
    hero: require('../../assets/recipes/borscht.jpg'),
    thumb: require('../../assets/recipes/borscht-thumb.jpg'),
  },
  'bouillabaisse': {
    hero: require('../../assets/recipes/bouillabaisse.jpg'),
    thumb: require('../../assets/recipes/bouillabaisse-thumb.jpg'),
  },
  'bruschetta': {
    hero: require('../../assets/recipes/bruschetta.jpg'),
    thumb: require('../../assets/recipes/bruschetta-thumb.jpg'),
  },
  'buffalo-wings': {
    hero: require('../../assets/recipes/buffalo-wings.jpg'),
    thumb: require('../../assets/recipes/buffalo-wings-thumb.jpg'),
  },
  'butter-chicken': {
    hero: require('../../assets/recipes/butter-chicken.jpg'),
    thumb: require('../../assets/recipes/butter-chicken-thumb.jpg'),
  },
  'cacio-e-pepe': {
    hero: require('../../assets/recipes/cacio-e-pepe.jpg'),
    thumb: require('../../assets/recipes/cacio-e-pepe-thumb.jpg'),
  },
  'caesar-salad': {
    hero: require('../../assets/recipes/caesar-salad.jpg'),
    thumb: require('../../assets/recipes/caesar-salad-thumb.jpg'),
  },
  'caprese': {
    hero: require('../../assets/recipes/caprese.jpg'),
    thumb: require('../../assets/recipes/caprese-thumb.jpg'),
  },
  'carbonara': {
    hero: require('../../assets/recipes/carbonara.jpg'),
    thumb: require('../../assets/recipes/carbonara-thumb.jpg'),
  },
  'cassoulet': {
    hero: require('../../assets/recipes/cassoulet.jpg'),
    thumb: require('../../assets/recipes/cassoulet-thumb.jpg'),
  },
  'char-siu': {
    hero: require('../../assets/recipes/char-siu.jpg'),
    thumb: require('../../assets/recipes/char-siu-thumb.jpg'),
  },
  'cheeseburger': {
    hero: require('../../assets/recipes/cheeseburger.jpg'),
    thumb: require('../../assets/recipes/cheeseburger-thumb.jpg'),
  },
  'churros': {
    hero: require('../../assets/recipes/churros.jpg'),
    thumb: require('../../assets/recipes/churros-thumb.jpg'),
  },
  'clam-chowder': {
    hero: require('../../assets/recipes/clam-chowder.jpg'),
    thumb: require('../../assets/recipes/clam-chowder-thumb.jpg'),
  },
  'congee': {
    hero: require('../../assets/recipes/congee.jpg'),
    thumb: require('../../assets/recipes/congee-thumb.jpg'),
  },
  'coq-au-vin': {
    hero: require('../../assets/recipes/coq-au-vin.jpg'),
    thumb: require('../../assets/recipes/coq-au-vin-thumb.jpg'),
  },
  'creme-brulee': {
    hero: require('../../assets/recipes/creme-brulee.jpg'),
    thumb: require('../../assets/recipes/creme-brulee-thumb.jpg'),
  },
  'crepes': {
    hero: require('../../assets/recipes/crepes.jpg'),
    thumb: require('../../assets/recipes/crepes-thumb.jpg'),
  },
  'croque-monsieur': {
    hero: require('../../assets/recipes/croque-monsieur.jpg'),
    thumb: require('../../assets/recipes/croque-monsieur-thumb.jpg'),
  },
  'croquetas': {
    hero: require('../../assets/recipes/croquetas.jpg'),
    thumb: require('../../assets/recipes/croquetas-thumb.jpg'),
  },
  'empanadas': {
    hero: require('../../assets/recipes/empanadas.jpg'),
    thumb: require('../../assets/recipes/empanadas-thumb.jpg'),
  },
  'fabada': {
    hero: require('../../assets/recipes/fabada.jpg'),
    thumb: require('../../assets/recipes/fabada-thumb.jpg'),
  },
  'falafel': {
    hero: require('../../assets/recipes/falafel.jpg'),
    thumb: require('../../assets/recipes/falafel-thumb.jpg'),
  },
  'feijoada': {
    hero: require('../../assets/recipes/feijoada.jpg'),
    thumb: require('../../assets/recipes/feijoada-thumb.jpg'),
  },
  'fish-and-chips': {
    hero: require('../../assets/recipes/fish-and-chips.jpg'),
    thumb: require('../../assets/recipes/fish-and-chips-thumb.jpg'),
  },
  'french-omelette': {
    hero: require('../../assets/recipes/french-omelette.jpg'),
    thumb: require('../../assets/recipes/french-omelette-thumb.jpg'),
  },
  'french-onion-soup': {
    hero: require('../../assets/recipes/french-onion-soup.jpg'),
    thumb: require('../../assets/recipes/french-onion-soup-thumb.jpg'),
  },
  'french-toast': {
    hero: require('../../assets/recipes/french-toast.jpg'),
    thumb: require('../../assets/recipes/french-toast-thumb.jpg'),
  },
  'fried-chicken': {
    hero: require('../../assets/recipes/fried-chicken.jpg'),
    thumb: require('../../assets/recipes/fried-chicken-thumb.jpg'),
  },
  'fried-rice': {
    hero: require('../../assets/recipes/fried-rice.jpg'),
    thumb: require('../../assets/recipes/fried-rice-thumb.jpg'),
  },
  'fried-shrimp': {
    hero: require('../../assets/recipes/fried-shrimp.jpg'),
    thumb: require('../../assets/recipes/fried-shrimp-thumb.jpg'),
  },
  'full-english': {
    hero: require('../../assets/recipes/full-english.jpg'),
    thumb: require('../../assets/recipes/full-english-thumb.jpg'),
  },
  'galbi': {
    hero: require('../../assets/recipes/galbi.jpg'),
    thumb: require('../../assets/recipes/galbi-thumb.jpg'),
  },
  'gambas-al-ajillo': {
    hero: require('../../assets/recipes/gambas-al-ajillo.jpg'),
    thumb: require('../../assets/recipes/gambas-al-ajillo-thumb.jpg'),
  },
  'gazpacho': {
    hero: require('../../assets/recipes/gazpacho.jpg'),
    thumb: require('../../assets/recipes/gazpacho-thumb.jpg'),
  },
  'gnocchi': {
    hero: require('../../assets/recipes/gnocchi.jpg'),
    thumb: require('../../assets/recipes/gnocchi-thumb.jpg'),
  },
  'goulash': {
    hero: require('../../assets/recipes/goulash.jpg'),
    thumb: require('../../assets/recipes/goulash-thumb.jpg'),
  },
  'gratin-dauphinois': {
    hero: require('../../assets/recipes/gratin-dauphinois.jpg'),
    thumb: require('../../assets/recipes/gratin-dauphinois-thumb.jpg'),
  },
  'greek-salad': {
    hero: require('../../assets/recipes/greek-salad.jpg'),
    thumb: require('../../assets/recipes/greek-salad-thumb.jpg'),
  },
  'green-curry': {
    hero: require('../../assets/recipes/green-curry.jpg'),
    thumb: require('../../assets/recipes/green-curry-thumb.jpg'),
  },
  'grilled-cheese': {
    hero: require('../../assets/recipes/grilled-cheese.jpg'),
    thumb: require('../../assets/recipes/grilled-cheese-thumb.jpg'),
  },
  'guacamole': {
    hero: require('../../assets/recipes/guacamole.jpg'),
    thumb: require('../../assets/recipes/guacamole-thumb.jpg'),
  },
  'gyoza': {
    hero: require('../../assets/recipes/gyoza.jpg'),
    thumb: require('../../assets/recipes/gyoza-thumb.jpg'),
  },
  'gyudon': {
    hero: require('../../assets/recipes/gyudon.jpg'),
    thumb: require('../../assets/recipes/gyudon-thumb.jpg'),
  },
  'hummus': {
    hero: require('../../assets/recipes/hummus.jpg'),
    thumb: require('../../assets/recipes/hummus-thumb.jpg'),
  },
  'jambalaya': {
    hero: require('../../assets/recipes/jambalaya.jpg'),
    thumb: require('../../assets/recipes/jambalaya-thumb.jpg'),
  },
  'japanese-curry': {
    hero: require('../../assets/recipes/japanese-curry.jpg'),
    thumb: require('../../assets/recipes/japanese-curry-thumb.jpg'),
  },
  'jollof-rice': {
    hero: require('../../assets/recipes/jollof-rice.jpg'),
    thumb: require('../../assets/recipes/jollof-rice-thumb.jpg'),
  },
  'karaage': {
    hero: require('../../assets/recipes/karaage.jpg'),
    thumb: require('../../assets/recipes/karaage-thumb.jpg'),
  },
  'kung-pao-chicken': {
    hero: require('../../assets/recipes/kung-pao-chicken.jpg'),
    thumb: require('../../assets/recipes/kung-pao-chicken-thumb.jpg'),
  },
  'lasagne': {
    hero: require('../../assets/recipes/lasagne.jpg'),
    thumb: require('../../assets/recipes/lasagne-thumb.jpg'),
  },
  'mac-and-cheese': {
    hero: require('../../assets/recipes/mac-and-cheese.jpg'),
    thumb: require('../../assets/recipes/mac-and-cheese-thumb.jpg'),
  },
  'mapo-tofu': {
    hero: require('../../assets/recipes/mapo-tofu.jpg'),
    thumb: require('../../assets/recipes/mapo-tofu-thumb.jpg'),
  },
  'minestrone': {
    hero: require('../../assets/recipes/minestrone.jpg'),
    thumb: require('../../assets/recipes/minestrone-thumb.jpg'),
  },
  'miso-soup': {
    hero: require('../../assets/recipes/miso-soup.jpg'),
    thumb: require('../../assets/recipes/miso-soup-thumb.jpg'),
  },
  'moules-mariniere': {
    hero: require('../../assets/recipes/moules-mariniere.jpg'),
    thumb: require('../../assets/recipes/moules-mariniere-thumb.jpg'),
  },
  'moussaka': {
    hero: require('../../assets/recipes/moussaka.jpg'),
    thumb: require('../../assets/recipes/moussaka-thumb.jpg'),
  },
  'okonomiyaki': {
    hero: require('../../assets/recipes/okonomiyaki.jpg'),
    thumb: require('../../assets/recipes/okonomiyaki-thumb.jpg'),
  },
  'onigiri': {
    hero: require('../../assets/recipes/onigiri.jpg'),
    thumb: require('../../assets/recipes/onigiri-thumb.jpg'),
  },
  'oyakodon': {
    hero: require('../../assets/recipes/oyakodon.jpg'),
    thumb: require('../../assets/recipes/oyakodon-thumb.jpg'),
  },
  'pad-thai': {
    hero: require('../../assets/recipes/pad-thai.jpg'),
    thumb: require('../../assets/recipes/pad-thai-thumb.jpg'),
  },
  'paella': {
    hero: require('../../assets/recipes/paella.jpg'),
    thumb: require('../../assets/recipes/paella-thumb.jpg'),
  },
  'pan-con-tomate': {
    hero: require('../../assets/recipes/pan-con-tomate.jpg'),
    thumb: require('../../assets/recipes/pan-con-tomate-thumb.jpg'),
  },
  'pancakes': {
    hero: require('../../assets/recipes/pancakes.jpg'),
    thumb: require('../../assets/recipes/pancakes-thumb.jpg'),
  },
  'patatas-bravas': {
    hero: require('../../assets/recipes/patatas-bravas.jpg'),
    thumb: require('../../assets/recipes/patatas-bravas-thumb.jpg'),
  },
  'pesto-genovese': {
    hero: require('../../assets/recipes/pesto-genovese.jpg'),
    thumb: require('../../assets/recipes/pesto-genovese-thumb.jpg'),
  },
  'pho': {
    hero: require('../../assets/recipes/pho.jpg'),
    thumb: require('../../assets/recipes/pho-thumb.jpg'),
  },
  'pizza-margherita': {
    hero: require('../../assets/recipes/pizza-margherita.jpg'),
    thumb: require('../../assets/recipes/pizza-margherita-thumb.jpg'),
  },
  'poke-bowl': {
    hero: require('../../assets/recipes/poke-bowl.jpg'),
    thumb: require('../../assets/recipes/poke-bowl-thumb.jpg'),
  },
  'porridge': {
    hero: require('../../assets/recipes/porridge.jpg'),
    thumb: require('../../assets/recipes/porridge-thumb.jpg'),
  },
  'poutine': {
    hero: require('../../assets/recipes/poutine.jpg'),
    thumb: require('../../assets/recipes/poutine-thumb.jpg'),
  },
  'puttanesca': {
    hero: require('../../assets/recipes/puttanesca.jpg'),
    thumb: require('../../assets/recipes/puttanesca-thumb.jpg'),
  },
  'quesadilla': {
    hero: require('../../assets/recipes/quesadilla.jpg'),
    thumb: require('../../assets/recipes/quesadilla-thumb.jpg'),
  },
  'quiche-lorraine': {
    hero: require('../../assets/recipes/quiche-lorraine.jpg'),
    thumb: require('../../assets/recipes/quiche-lorraine-thumb.jpg'),
  },
  'ramen': {
    hero: require('../../assets/recipes/ramen.jpg'),
    thumb: require('../../assets/recipes/ramen-thumb.jpg'),
  },
  'risotto-milanese': {
    hero: require('../../assets/recipes/risotto-milanese.jpg'),
    thumb: require('../../assets/recipes/risotto-milanese-thumb.jpg'),
  },
  'salade-nicoise': {
    hero: require('../../assets/recipes/salade-nicoise.jpg'),
    thumb: require('../../assets/recipes/salade-nicoise-thumb.jpg'),
  },
  'salmorejo': {
    hero: require('../../assets/recipes/salmorejo.jpg'),
    thumb: require('../../assets/recipes/salmorejo-thumb.jpg'),
  },
  'scrambled-eggs': {
    hero: require('../../assets/recipes/scrambled-eggs.jpg'),
    thumb: require('../../assets/recipes/scrambled-eggs-thumb.jpg'),
  },
  'shakshuka': {
    hero: require('../../assets/recipes/shakshuka.jpg'),
    thumb: require('../../assets/recipes/shakshuka-thumb.jpg'),
  },
  'shawarma': {
    hero: require('../../assets/recipes/shawarma.jpg'),
    thumb: require('../../assets/recipes/shawarma-thumb.jpg'),
  },
  'shepherds-pie': {
    hero: require('../../assets/recipes/shepherds-pie.jpg'),
    thumb: require('../../assets/recipes/shepherds-pie-thumb.jpg'),
  },
  'sukiyaki': {
    hero: require('../../assets/recipes/sukiyaki.jpg'),
    thumb: require('../../assets/recipes/sukiyaki-thumb.jpg'),
  },
  'tacos-al-pastor': {
    hero: require('../../assets/recipes/tacos-al-pastor.jpg'),
    thumb: require('../../assets/recipes/tacos-al-pastor-thumb.jpg'),
  },
  'tamagoyaki': {
    hero: require('../../assets/recipes/tamagoyaki.jpg'),
    thumb: require('../../assets/recipes/tamagoyaki-thumb.jpg'),
  },
  'tarte-tatin': {
    hero: require('../../assets/recipes/tarte-tatin.jpg'),
    thumb: require('../../assets/recipes/tarte-tatin-thumb.jpg'),
  },
  'tikka-masala': {
    hero: require('../../assets/recipes/tikka-masala.jpg'),
    thumb: require('../../assets/recipes/tikka-masala-thumb.jpg'),
  },
  'tiramisu': {
    hero: require('../../assets/recipes/tiramisu.jpg'),
    thumb: require('../../assets/recipes/tiramisu-thumb.jpg'),
  },
  'tonkatsu': {
    hero: require('../../assets/recipes/tonkatsu.jpg'),
    thumb: require('../../assets/recipes/tonkatsu-thumb.jpg'),
  },
  'tortilla-espanola': {
    hero: require('../../assets/recipes/tortilla-espanola.jpg'),
    thumb: require('../../assets/recipes/tortilla-espanola-thumb.jpg'),
  },
  'waffles': {
    hero: require('../../assets/recipes/waffles.jpg'),
    thumb: require('../../assets/recipes/waffles-thumb.jpg'),
  },
  'yakitori': {
    hero: require('../../assets/recipes/yakitori.jpg'),
    thumb: require('../../assets/recipes/yakitori-thumb.jpg'),
  },
};

/** The photograph for a recipe, or null if the slug is not in the library. */
export function recipeImage(slug: string): RecipeImageAssets | null {
  return recipeImages[slug] ?? null;
}
