/**
 * Typed access to the curated recipe library.
 *
 * Generated by scripts/build_recipe_subset.py from the 704 MB Food.com export.
 * The selection is stratified across cuisine and meal slot so the planner has
 * real choices in every direction the onboarding can point it.
 */

import ingredientData from './generated/ingredients.json';
import recipeData from './generated/recipes.json';
import type { Ingredient } from '@/domain/pantry/types';
import type { DietType } from '@/domain/nutrition/types';
import type { Recipe } from '@/domain/planner/types';

export const recipes = recipeData as unknown as Recipe[];

const ingredientPayload = ingredientData as unknown as {
  ingredients: Ingredient[];
  categories: Record<string, { aisle: string; staple: boolean }>;
  cuisine_labels: Record<string, string>;
};

export const ingredients = ingredientPayload.ingredients;
export const cuisineLabels = ingredientPayload.cuisine_labels;

export const ingredientsById: Record<string, Ingredient> = Object.fromEntries(
  ingredients.map((ingredient) => [ingredient.id, ingredient]),
);

export const recipesById = new Map<number, Recipe>(
  recipes.map((recipe) => [recipe.id, recipe]),
);

/** Cuisines actually present in the library, with counts, most common first. */
export const availableCuisines = (() => {
  const counts = new Map<string, number>();
  for (const recipe of recipes) {
    counts.set(recipe.cuisine, (counts.get(recipe.cuisine) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([id, count]) => ({
      id,
      label: cuisineLabels[id] ?? id,
      count,
    }))
    .filter((entry) => entry.id !== 'unspecified')
    .sort((a, b) => b.count - a.count);
})();

/** How many recipes remain for a given diet. Drives the thin-library warning. */
export function recipeCountForDiet(diet: DietType): number {
  return recipes.filter((recipe) => recipe.diet[diet]).length;
}

/**
 * Diets with too few recipes to build a varied plan.
 *
 * The Food.com corpus has almost nothing that is purely animal products, so a
 * carnivore plan draws from a very small pool. The app says so rather than
 * quietly serving the same four dishes.
 */
export const THIN_LIBRARY_THRESHOLD = 60;

export function isLibraryThin(diet: DietType): boolean {
  return recipeCountForDiet(diet) < THIN_LIBRARY_THRESHOLD;
}
